/* usrFmanSoftParse.c - Configlette for P4080 frame manager soft parser */

/*
 * Copyright (c) 2010 Wind River Systems, Inc.
 *
 * The right to copy, distribute, modify or otherwise make use
 * of this software may be licensed only pursuant to the terms
 * of an applicable Wind River license agreement.
 */


/*
modification history
--------------------
01a,10mar10,wap  created
*/

/*
DESCRIPTION

This file is used to compile P4080 soft parser programs generated by the
Freescale FMC tool into VxWorks. It also loads the soft parser programs
into the frame manager driver.

The required components are:

DRV_RESOURCE_QORIQQMAN
DRV_RESOURCE_QORIQBMAN
DRV_RESOURCE_QORIQFMAN
DRV_RESOURCE_QORIQFMAN_SOFTPARSE

NOMANUAL
*/

#include <vxWorks.h>

#include <hwif/vxbus/vxBus.h>
#include <hwif/util/vxbParamSys.h>

#include <../src/hwif/h/resource/vxbQorIQQmanPortal.h>
#include <../src/hwif/h/resource/vxbQorIQBmanPortal.h>
#include <../src/hwif/h/resource/vxbQorIQFman.h>

/*
 * This is a compatibility tweak to allow the FMC-generated code to more
 * easily compile in VxWorks.
 */

#define uint8_t UINT8

/*
 * The softparse.h file is generated by the Freescale FMC tool. It contains the
 * initialization for an FMAN_SP_PARAMS structure that includes binary code
 * for the soft parser engine. The input to the FMC tool is an XML file that
 * contains a protocol definition. The softparse.h file can be generated from
 * the XML with the following command:
 *
 * % fmc -s protocol.xml --sp_only
 *
 * Note: the softparse.h file must exist in order for this code to
 * compile correctly.
 */

#include "softparse.h"

FMAN_SP_PARAMS spCode = SOFT_PARSE_CODE;

STATUS usrFmanProgLoad
    (
    VXB_DEVICE_ID pDev
    )
    {
    return (fmanPrSpFmcProgLoad (pDev, &spCode));
    }

void usrFmanSoftParseInit (void)
    {
    VXB_DEVICE_ID pDev;

    pDev = vxbInstByNameFind ("QorIQFman", 0);
    if (pDev != NULL)
        usrFmanProgLoad (pDev);

    pDev = vxbInstByNameFind ("QorIQFman", 1);
    if (pDev != NULL)
        usrFmanProgLoad (pDev);

    return;
    }
