/* 01profile_development.cdf - VxWorks Development Kernel Config Profile */

/*
 * Copyright (c) 2004-2010, 2013 Wind River Systems, Inc.
 *
 * The right to copy, distribute, modify or otherwise make use
 * of this software may be licensed only pursuant to the terms
 * of an applicable Wind River license agreement.
 */

/*
modification history
--------------------
02a,25apr13,rbc  WIND00414401 - Changes to support Unified BSP.
01z,20dec10,rlp  Removed more WDB components + Windview from standalone
                 profile (WIND00247260).
01y,07dec10,mze  tweaks
01x,06dec10,mze  adding an ST development profile
01w,12nov10,mze  _WRS_VX_SMP is now obsolete replaced with _WRS_CONFIG_SMP
01v,06oct10,gls  added INCLUDE_EDR_POLICY_HOOKS (WIND00234560)
01u,30dec09,jpb  Remove INCLUDE_TASK_VARS from LP64 build.
01t,06feb09,rlp  Added WDB dynamic printf support (CQ:WIND00155075).
01s,04oct07,mze  fix for 104829
01r,30aug07,kk   fixed #ifndef within listing which causes listings after to
                 not get pulled in
01q,16aug07,pch  remove INCLUDE_TASK_VARS from SMP build
01p,03jul07,rlp  Removed INCLUDE_BUF_MGR component.
01o,22nov06,kch  Removed coreip telnet server.
01n,18sep06,tkf  Remove INCLUDE_NET_BOOT_CONFIG and INCLUDE_NET_INIT
                 (WIND00065689).
01m,10sep06,tkf  Removed more obsolete components.
01l,06sep06,tkf  Removed INCLUDE_DOMAIN_INIT, INCLUDE_ICMPV4.
01k,09jan06,pee  added BSP_DEFAULT for scalable BSPs
01j,06aug05,jln  added INCLUDE_VX_NATIVE_SCHEDULER
01i,01aug05,yvp  Added newly created components (sem, msgQ & wd create/delete).
01h,09jul05,yvp  Added newly created components.
01g,23mar05,vvv  removed obsolete INCLUDE_NET_GETOPT
01f,08mar05,dlk  Replace obsolete INCLUDE_NET_APPUTIL with 
                 INCLUDE_APPL_LOG_UTIL.
01e,22nov04,zl   added some kernel hardening components.
01d,16nov04,tam  removed BSP specific components
01c,11oct04,jn   Change name of INCLUDE_ABS_SYMBOLS to INCLUDE_OFFSET_SYMBOLS
01b,01oct04,fle  turned it into a Profile
                 + renamed INCLUDE_RTP_KERNEL into INCLUDE_BASE_KERNEL
01a,16sep04,pee  written
*/

/*
 * ****************************************************************
 * WARNING WARNING WARNING WARNING
 * ****************************************************************
 *
 * When updating the COMPONENTS listing in this profile,
 * please note there are 2 listings: one for UP and one for SMP.
 * If your new component applies to both SMP and UP, please
 * update both lists.
 */

Profile PROFILE_DEVELOPMENT
    {
    NAME	VxWorks Kernel Development Configuration Profile
    SYNOPSIS	VxWorks kernel including development and debugging components
    PROFILES    BSP_DEFAULT
#if (defined _WRS_CONFIG_SMP) || (defined _WRS_CONFIG_LP64)
    COMPONENTS	INCLUDE_ANSI_ASSERT \
		INCLUDE_ANSI_CTYPE \
		INCLUDE_ANSI_LOCALE \
		INCLUDE_ANSI_MATH \
		INCLUDE_ANSI_STDIO \
		INCLUDE_ANSI_STDIO_EXTRA \
		INCLUDE_ANSI_STDLIB \
		INCLUDE_ANSI_STRING \
		INCLUDE_ANSI_TIME \
		INCLUDE_APPL_LOG_UTIL \
		INCLUDE_BASE_KERNEL \
		INCLUDE_BOOT_LINE_INIT \
		INCLUDE_BSD_SOCKET \
		INCLUDE_BSP_MACROS \
		INCLUDE_CACHE_ENABLE \
		INCLUDE_CPLUS \
		INCLUDE_CPLUS_LANG \
		INCLUDE_CTORS_DTORS \
		INCLUDE_DEBUG \
		INCLUDE_DEFERRED_INTERRUPT_ENABLE \
		INCLUDE_DHCPC_LEASE_CLEAN \
		INCLUDE_DIAB_INTRINSICS \
		INCLUDE_DISK_UTIL \
		INCLUDE_EDR_POLICY_HOOKS \
		INCLUDE_EDR_STUB \
		INCLUDE_EDR_SYSDBG_FLAG \
		INCLUDE_END \
		INCLUDE_ENV_VARS \
		INCLUDE_ETHERNET \
		INCLUDE_EXC_HANDLING \
		INCLUDE_EXC_SHOW \
		INCLUDE_EXC_TASK \
		INCLUDE_FLOATING_POINT \
		INCLUDE_FORMATTED_IO \
		INCLUDE_GETSERVBYNAME \
		INCLUDE_GNU_INTRINSICS \
		INCLUDE_GTF \
		INCLUDE_GTF_TIMER_START \
		INCLUDE_HASH \
		INCLUDE_HOOKS \
		INCLUDE_HOST_TBL \
		INCLUDE_ISR_OBJECTS \
		INCLUDE_INETLIB \
		INCLUDE_IO_SYSTEM \
		INCLUDE_IPATTACH \
		INCLUDE_IPV4 \
		INCLUDE_JOB_TASK \
		INCLUDE_KERNEL \
		INCLUDE_VX_NATIVE_SCHEDULER \
		INCLUDE_LINKBUFPOOL \
		INCLUDE_LOADER \
		INCLUDE_LOGGING \
		INCLUDE_MEMORY_CONFIG \
		INCLUDE_MEM_MGR_BASIC \
		INCLUDE_MEM_MGR_FULL \
		INCLUDE_MEM_SHOW \
		INCLUDE_MIB2_IF \
		INCLUDE_MSG_Q \
		INCLUDE_MSG_Q_CREATE_DELETE \
		INCLUDE_MSG_Q_INFO \
		INCLUDE_MSG_Q_SHOW \
		INCLUDE_MUX \
		INCLUDE_NETBUFLIB \
		INCLUDE_NETBUFPOOL \
		INCLUDE_NETWORK \
		INCLUDE_NET_BOOT \
		INCLUDE_NET_DAEMON \
		INCLUDE_NET_DRV \
		INCLUDE_NET_HOST_SETUP \
		INCLUDE_OBJ_OWNERSHIP \
		INCLUDE_OFFSET_SYMBOLS \
		INCLUDE_POSIX_CLOCKS \
		INCLUDE_POSIX_DIRLIB \
		INCLUDE_PROTECT_TASK_STACK \
		INCLUDE_REBOOT_HOOKS \
		INCLUDE_REMLIB \
		INCLUDE_ROMFS \
        	INCLUDE_RTP \
		INCLUDE_RTP_APPL_INIT_BOOTLINE \
		INCLUDE_RTP_APPL_USER \
		INCLUDE_RTP_SHOW \
		INCLUDE_RTP_HOOKS \
		INCLUDE_RTP_SHELL_CMD \
		INCLUDE_SELECT \
		INCLUDE_SELECT_SUPPORT \
		INCLUDE_SEM_BINARY \
		INCLUDE_SEM_COUNTING \
		INCLUDE_SEM_MUTEX \
		INCLUDE_SEM_LIB \
		INCLUDE_SEM_DELETE \
		INCLUDE_SEM_BINARY_CREATE \
		INCLUDE_SEM_COUNTING_CREATE \
		INCLUDE_SEM_MUTEX_CREATE \
		INCLUDE_SHARED_DATA \
		INCLUDE_SHARED_DATA_SHOW \
		INCLUDE_SHELL \
		INCLUDE_SHELL_EMACS_MODE \
		INCLUDE_SHELL_INTERP_C \
		INCLUDE_SHELL_INTERP_CMD \
		INCLUDE_SHELL_VI_MODE \
		INCLUDE_SHELL_EMACS_MODE \
		INCLUDE_SHELL_VI_MODE \
		INCLUDE_SHL \
		INCLUDE_SHL_SHOW \
		INCLUDE_SHL_SHELL_CMD \
		INCLUDE_SHOW_ROUTINES \
		INCLUDE_SIGNALS \
		INCLUDE_SIO \
		INCLUDE_SOCKLIB \
		INCLUDE_NET_SYM_TBL \
		INCLUDE_STARTUP_SCRIPT \
		INCLUDE_STAT_SYM_TBL \
		INCLUDE_STDIO \
		INCLUDE_STRICMP \
		INCLUDE_SYM_TBL \
		INCLUDE_SYM_TBL_SHOW \
		INCLUDE_SYSCLK_INIT \
        	INCLUDE_SYSCTL \
		INCLUDE_SYSHW_INIT \
		INCLUDE_SYS_START \
		INCLUDE_TASK_CREATE_DELETE \
		INCLUDE_TASK_HOOKS \
		INCLUDE_TASK_RESTART \
		INCLUDE_TASK_STACK_NO_EXEC \
		INCLUDE_TCPV4 \
		INCLUDE_TIMESTAMP \
		INCLUDE_TIMEX \
		INCLUDE_TRIGGERING \
		INCLUDE_TTY_DEV \
		INCLUDE_TYLIB \
		INCLUDE_UDPV4 \
		INCLUDE_UNLOADER \
		INCLUDE_USER_APPL \
		INCLUDE_VXEVENTS \
		INCLUDE_WATCHDOGS \
		INCLUDE_WATCHDOGS_CREATE_DELETE \
		INCLUDE_WDB \
		INCLUDE_WDB_BANNER \
		INCLUDE_WDB_BP \
		INCLUDE_WDB_CTXT \
		INCLUDE_WDB_DIRECT_CALL \
		INCLUDE_WDB_DPRINTF \
		INCLUDE_WDB_EVENTPOINTS \
		INCLUDE_WDB_EVENTS \
		INCLUDE_WDB_EXC_NOTIFY \
		INCLUDE_WDB_EXIT_NOTIFY \
		INCLUDE_WDB_FUNC_CALL \
		INCLUDE_WDB_GOPHER \
		INCLUDE_WDB_MEM \
		INCLUDE_WDB_POST_KERNEL_INIT \
		INCLUDE_WDB_REG \
		INCLUDE_WDB_START_NOTIFY \
		INCLUDE_WDB_SYS \
		INCLUDE_WDB_TASK \
		INCLUDE_WDB_TASK_BP \
		INCLUDE_WDB_TASK_HOOKS \
		INCLUDE_WDB_TSFS \
		INCLUDE_WDB_USER_EVENT \
		INCLUDE_WDB_VIO \
		INCLUDE_WDB_VIO_LIB \
		INCLUDE_WINDVIEW \
		INCLUDE_WVUPLOAD_FILE \
		INCLUDE_WVUPLOAD_TSFSSOCK \
		INCLUDE_XDR
#else /* !_WRS_CONFIG_SMP && ! _WRS_CONFIG_LP64 */
    COMPONENTS	INCLUDE_ANSI_ASSERT \
		INCLUDE_ANSI_CTYPE \
		INCLUDE_ANSI_LOCALE \
		INCLUDE_ANSI_MATH \
		INCLUDE_ANSI_STDIO \
		INCLUDE_ANSI_STDIO_EXTRA \
		INCLUDE_ANSI_STDLIB \
		INCLUDE_ANSI_STRING \
		INCLUDE_ANSI_TIME \
		INCLUDE_APPL_LOG_UTIL \
		INCLUDE_BASE_KERNEL \
		INCLUDE_BOOT_LINE_INIT \
		INCLUDE_BSD_SOCKET \
		INCLUDE_BSP_MACROS \
		INCLUDE_CACHE_ENABLE \
		INCLUDE_CPLUS \
		INCLUDE_CPLUS_LANG \
		INCLUDE_CTORS_DTORS \
		INCLUDE_DEBUG \
		INCLUDE_DEFERRED_INTERRUPT_ENABLE \
		INCLUDE_DHCPC_LEASE_CLEAN \
		INCLUDE_DIAB_INTRINSICS \
		INCLUDE_DISK_UTIL \
		INCLUDE_EDR_POLICY_HOOKS \
		INCLUDE_EDR_STUB \
		INCLUDE_EDR_SYSDBG_FLAG \
		INCLUDE_END \
		INCLUDE_ENV_VARS \
		INCLUDE_ETHERNET \
		INCLUDE_EXC_HANDLING \
		INCLUDE_EXC_SHOW \
		INCLUDE_EXC_TASK \
		INCLUDE_FLOATING_POINT \
		INCLUDE_FORMATTED_IO \
		INCLUDE_GETSERVBYNAME \
		INCLUDE_GNU_INTRINSICS \
		INCLUDE_GTF \
		INCLUDE_GTF_TIMER_START \
		INCLUDE_HASH \
		INCLUDE_HOOKS \
		INCLUDE_HOST_TBL \
		INCLUDE_ISR_OBJECTS \
		INCLUDE_INETLIB \
		INCLUDE_IO_SYSTEM \
		INCLUDE_IPATTACH \
		INCLUDE_IPV4 \
		INCLUDE_JOB_TASK \
		INCLUDE_KERNEL \
		INCLUDE_VX_NATIVE_SCHEDULER \
		INCLUDE_LINKBUFPOOL \
		INCLUDE_LOADER \
		INCLUDE_LOGGING \
		INCLUDE_MEMORY_CONFIG \
		INCLUDE_MEM_MGR_BASIC \
		INCLUDE_MEM_MGR_FULL \
		INCLUDE_MEM_SHOW \
		INCLUDE_MIB2_IF \
		INCLUDE_MSG_Q \
		INCLUDE_MSG_Q_CREATE_DELETE \
		INCLUDE_MSG_Q_INFO \
		INCLUDE_MSG_Q_SHOW \
		INCLUDE_MUX \
		INCLUDE_NETBUFLIB \
		INCLUDE_NETBUFPOOL \
		INCLUDE_NETWORK \
		INCLUDE_NET_BOOT \
		INCLUDE_NET_DAEMON \
		INCLUDE_NET_DRV \
		INCLUDE_NET_HOST_SETUP \
		INCLUDE_OBJ_OWNERSHIP \
		INCLUDE_OFFSET_SYMBOLS \
		INCLUDE_POSIX_CLOCKS \
		INCLUDE_POSIX_DIRLIB \
		INCLUDE_PROTECT_TASK_STACK \
		INCLUDE_REBOOT_HOOKS \
		INCLUDE_REMLIB \
		INCLUDE_ROMFS \
        	INCLUDE_RTP \
		INCLUDE_RTP_APPL_INIT_BOOTLINE \
		INCLUDE_RTP_APPL_USER \
		INCLUDE_RTP_SHOW \
		INCLUDE_RTP_HOOKS \
		INCLUDE_RTP_SHELL_CMD \
		INCLUDE_SELECT \
		INCLUDE_SELECT_SUPPORT \
		INCLUDE_SEM_BINARY \
		INCLUDE_SEM_COUNTING \
		INCLUDE_SEM_MUTEX \
		INCLUDE_SEM_LIB \
		INCLUDE_SEM_DELETE \
		INCLUDE_SEM_BINARY_CREATE \
		INCLUDE_SEM_COUNTING_CREATE \
		INCLUDE_SEM_MUTEX_CREATE \
		INCLUDE_SHARED_DATA \
		INCLUDE_SHARED_DATA_SHOW \
		INCLUDE_SHELL \
		INCLUDE_SHELL_EMACS_MODE \
		INCLUDE_SHELL_INTERP_C \
		INCLUDE_SHELL_INTERP_CMD \
		INCLUDE_SHELL_VI_MODE \
		INCLUDE_SHELL_EMACS_MODE \
		INCLUDE_SHELL_VI_MODE \
		INCLUDE_SHL \
		INCLUDE_SHL_SHOW \
		INCLUDE_SHL_SHELL_CMD \
		INCLUDE_SHOW_ROUTINES \
		INCLUDE_SIGNALS \
		INCLUDE_SIO \
		INCLUDE_SOCKLIB \
		INCLUDE_NET_SYM_TBL \
		INCLUDE_STARTUP_SCRIPT \
		INCLUDE_STAT_SYM_TBL \
		INCLUDE_STDIO \
		INCLUDE_STRICMP \
		INCLUDE_SYM_TBL \
		INCLUDE_SYM_TBL_SHOW \
		INCLUDE_SYSCLK_INIT \
        	INCLUDE_SYSCTL \
		INCLUDE_SYSHW_INIT \
		INCLUDE_SYS_START \
		INCLUDE_TASK_CREATE_DELETE \
		INCLUDE_TASK_HOOKS \
		INCLUDE_TASK_RESTART \
		INCLUDE_TASK_STACK_NO_EXEC \
		INCLUDE_TASK_VARS \
		INCLUDE_TCPV4 \
		INCLUDE_TIMESTAMP \
		INCLUDE_TIMEX \
		INCLUDE_TRIGGERING \
		INCLUDE_TTY_DEV \
		INCLUDE_TYLIB \
		INCLUDE_UDPV4 \
		INCLUDE_UNLOADER \
		INCLUDE_USER_APPL \
		INCLUDE_VXEVENTS \
		INCLUDE_WATCHDOGS \
		INCLUDE_WATCHDOGS_CREATE_DELETE \
		INCLUDE_WDB \
		INCLUDE_WDB_BANNER \
		INCLUDE_WDB_BP \
		INCLUDE_WDB_CTXT \
		INCLUDE_WDB_DIRECT_CALL \
		INCLUDE_WDB_DPRINTF \
		INCLUDE_WDB_EVENTPOINTS \
		INCLUDE_WDB_EVENTS \
		INCLUDE_WDB_EXC_NOTIFY \
		INCLUDE_WDB_EXIT_NOTIFY \
		INCLUDE_WDB_FUNC_CALL \
		INCLUDE_WDB_GOPHER \
		INCLUDE_WDB_MEM \
		INCLUDE_WDB_POST_KERNEL_INIT \
		INCLUDE_WDB_REG \
		INCLUDE_WDB_START_NOTIFY \
		INCLUDE_WDB_SYS \
		INCLUDE_WDB_TASK \
		INCLUDE_WDB_TASK_BP \
		INCLUDE_WDB_TASK_HOOKS \
		INCLUDE_WDB_TSFS \
		INCLUDE_WDB_USER_EVENT \
		INCLUDE_WDB_VIO \
		INCLUDE_WDB_VIO_LIB \
		INCLUDE_WINDVIEW \
		INCLUDE_WVUPLOAD_FILE \
		INCLUDE_WVUPLOAD_TSFSSOCK \
		INCLUDE_XDR
#endif /* _WRS_CONFIG_SMP || _WRS_CONFIG_LP64 */
    _CHILDREN	FOLDER_NOT_VISIBLE
    }
    
Profile PROFILE_STANDALONE_DEVELOPMENT
    {
    NAME	VxWorks Kernel Standalone Development Configuration Profile
    SYNOPSIS	VxWorks kernel including development and debugging components with symbol table included.
    PROFILES    BSP_DEFAULT
#if (defined _WRS_CONFIG_SMP) || (defined _WRS_CONFIG_LP64)
    COMPONENTS	INCLUDE_ANSI_ASSERT \
		INCLUDE_ANSI_CTYPE \
		INCLUDE_ANSI_LOCALE \
		INCLUDE_ANSI_MATH \
		INCLUDE_ANSI_STDIO \
		INCLUDE_ANSI_STDIO_EXTRA \
		INCLUDE_ANSI_STDLIB \
		INCLUDE_ANSI_STRING \
		INCLUDE_ANSI_TIME \
		INCLUDE_APPL_LOG_UTIL \
		INCLUDE_BASE_KERNEL \
		INCLUDE_BOOT_LINE_INIT \
		INCLUDE_BSD_SOCKET \
		INCLUDE_BSP_MACROS \
		INCLUDE_CACHE_ENABLE \
		INCLUDE_CPLUS \
		INCLUDE_CPLUS_LANG \
		INCLUDE_CTORS_DTORS \
		INCLUDE_DEBUG \
		INCLUDE_DEFERRED_INTERRUPT_ENABLE \
		INCLUDE_DHCPC_LEASE_CLEAN \
		INCLUDE_DIAB_INTRINSICS \
		INCLUDE_DISK_UTIL \
		INCLUDE_EDR_POLICY_HOOKS \
		INCLUDE_EDR_STUB \
		INCLUDE_EDR_SYSDBG_FLAG \
		INCLUDE_END \
		INCLUDE_ENV_VARS \
		INCLUDE_ETHERNET \
		INCLUDE_EXC_HANDLING \
		INCLUDE_EXC_SHOW \
		INCLUDE_EXC_TASK \
		INCLUDE_FLOATING_POINT \
		INCLUDE_FORMATTED_IO \
		INCLUDE_GETSERVBYNAME \
		INCLUDE_GNU_INTRINSICS \
		INCLUDE_GTF \
		INCLUDE_GTF_TIMER_START \
		INCLUDE_HASH \
		INCLUDE_HOOKS \
		INCLUDE_HOST_TBL \
		INCLUDE_IFCONFIG \
		INCLUDE_ISR_OBJECTS \
		INCLUDE_INETLIB \
		INCLUDE_IO_SYSTEM \
		INCLUDE_IPATTACH \
		INCLUDE_IPV4 \
		INCLUDE_JOB_TASK \
		INCLUDE_KERNEL \
		INCLUDE_VX_NATIVE_SCHEDULER \
		INCLUDE_LINKBUFPOOL \
		INCLUDE_LOADER \
		INCLUDE_LOGGING \
		INCLUDE_MEMORY_CONFIG \
		INCLUDE_MEM_MGR_BASIC \
		INCLUDE_MEM_MGR_FULL \
		INCLUDE_MEM_SHOW \
		INCLUDE_MIB2_IF \
		INCLUDE_MSG_Q \
		INCLUDE_MSG_Q_CREATE_DELETE \
		INCLUDE_MSG_Q_INFO \
		INCLUDE_MSG_Q_SHOW \
		INCLUDE_MUX \
		INCLUDE_NETBUFLIB \
		INCLUDE_NETBUFPOOL \
		INCLUDE_NETWORK \
		INCLUDE_NET_BOOT \
		INCLUDE_NET_DAEMON \
		INCLUDE_NET_DRV \
		INCLUDE_NET_HOST_SETUP \
		INCLUDE_OBJ_OWNERSHIP \
		INCLUDE_OFFSET_SYMBOLS \
		INCLUDE_PCI_BUS_SHOW \
		INCLUDE_PING \
		INCLUDE_POSIX_CLOCKS \
		INCLUDE_POSIX_DIRLIB \
		INCLUDE_PROTECT_TASK_STACK \
		INCLUDE_REBOOT_HOOKS \
		INCLUDE_REMLIB \
		INCLUDE_ROMFS \
        	INCLUDE_RTP \
		INCLUDE_RTP_APPL_INIT_BOOTLINE \
		INCLUDE_RTP_APPL_USER \
		INCLUDE_RTP_SHOW \
		INCLUDE_RTP_HOOKS \
		INCLUDE_RTP_SHELL_CMD \
		INCLUDE_SELECT \
		INCLUDE_SELECT_SUPPORT \
		INCLUDE_SEM_BINARY \
		INCLUDE_SEM_COUNTING \
		INCLUDE_SEM_MUTEX \
		INCLUDE_SEM_LIB \
		INCLUDE_SEM_DELETE \
		INCLUDE_SEM_BINARY_CREATE \
		INCLUDE_SEM_COUNTING_CREATE \
		INCLUDE_SEM_MUTEX_CREATE \
		INCLUDE_SHARED_DATA \
		INCLUDE_SHARED_DATA_SHOW \
		INCLUDE_SHELL \
		INCLUDE_SHELL_EMACS_MODE \
		INCLUDE_SHELL_INTERP_C \
		INCLUDE_SHELL_INTERP_CMD \
		INCLUDE_SHELL_VI_MODE \
		INCLUDE_SHELL_EMACS_MODE \
		INCLUDE_SHELL_VI_MODE \
		INCLUDE_SHL \
		INCLUDE_SHL_SHOW \
		INCLUDE_SHL_SHELL_CMD \
		INCLUDE_SHOW_ROUTINES \
		INCLUDE_SIGNALS \
		INCLUDE_SIO \
		INCLUDE_SOCKLIB \
                INCLUDE_STARTUP_SCRIPT \
		INCLUDE_STAT_SYM_TBL \
		INCLUDE_STDIO \
		INCLUDE_STRICMP \
		INCLUDE_STANDALONE_SYM_TBL \
		INCLUDE_SYM_TBL \
		INCLUDE_SYM_TBL_SHOW \
		INCLUDE_SYSCLK_INIT \
        	INCLUDE_SYSCTL \
		INCLUDE_SYSHW_INIT \
		INCLUDE_SYS_START \
		INCLUDE_TASK_CREATE_DELETE \
		INCLUDE_TASK_HOOKS \
		INCLUDE_TASK_RESTART \
		INCLUDE_TASK_STACK_NO_EXEC \
		INCLUDE_TCPV4 \
		INCLUDE_TIMER_SYS_SHOW \
		INCLUDE_TIMESTAMP \
		INCLUDE_TIMEX \
		INCLUDE_TRIGGERING \
		INCLUDE_TTY_DEV \
		INCLUDE_TYLIB \
		INCLUDE_UDPV4 \
		INCLUDE_UNLOADER \
		INCLUDE_USER_APPL \
		INCLUDE_VXBUS_SHOW \
		INCLUDE_VXEVENTS \
		INCLUDE_WATCHDOGS \
		INCLUDE_WATCHDOGS_CREATE_DELETE \
		INCLUDE_WDB \
		INCLUDE_WDB_BANNER \
		INCLUDE_WDB_BP \
		INCLUDE_WDB_CTXT \
		INCLUDE_WDB_DIRECT_CALL \
		INCLUDE_WDB_DPRINTF \
		INCLUDE_WDB_EVENTPOINTS \
		INCLUDE_WDB_EVENTS \
		INCLUDE_WDB_EXC_NOTIFY \
		INCLUDE_WDB_EXIT_NOTIFY \
		INCLUDE_WDB_FUNC_CALL \
		INCLUDE_WDB_GOPHER \
		INCLUDE_WDB_MEM \
		INCLUDE_WDB_POST_KERNEL_INIT \
		INCLUDE_WDB_REG \
		INCLUDE_WDB_START_NOTIFY \
		INCLUDE_WDB_SYS \
		INCLUDE_WDB_TASK \
		INCLUDE_WDB_TASK_BP \
		INCLUDE_WDB_TASK_HOOKS \
		INCLUDE_WDB_TSFS \
		INCLUDE_WDB_USER_EVENT \
		INCLUDE_WDB_VIO \
		INCLUDE_WDB_VIO_LIB \
                INCLUDE_XDR
#else /* !_WRS_CONFIG_SMP && ! _WRS_CONFIG_LP64 */
    COMPONENTS	INCLUDE_ANSI_ASSERT \
		INCLUDE_ANSI_CTYPE \
		INCLUDE_ANSI_LOCALE \
		INCLUDE_ANSI_MATH \
		INCLUDE_ANSI_STDIO \
		INCLUDE_ANSI_STDIO_EXTRA \
		INCLUDE_ANSI_STDLIB \
		INCLUDE_ANSI_STRING \
		INCLUDE_ANSI_TIME \
		INCLUDE_APPL_LOG_UTIL \
		INCLUDE_BASE_KERNEL \
		INCLUDE_BOOT_LINE_INIT \
		INCLUDE_BSD_SOCKET \
		INCLUDE_BSP_MACROS \
		INCLUDE_CACHE_ENABLE \
		INCLUDE_CPLUS \
		INCLUDE_CPLUS_LANG \
		INCLUDE_CTORS_DTORS \
		INCLUDE_DEBUG \
		INCLUDE_DEFERRED_INTERRUPT_ENABLE \
		INCLUDE_DHCPC_LEASE_CLEAN \
		INCLUDE_DIAB_INTRINSICS \
		INCLUDE_DISK_UTIL \
		INCLUDE_EDR_POLICY_HOOKS \
		INCLUDE_EDR_STUB \
		INCLUDE_EDR_SYSDBG_FLAG \
		INCLUDE_END \
		INCLUDE_ENV_VARS \
		INCLUDE_ETHERNET \
		INCLUDE_EXC_HANDLING \
		INCLUDE_EXC_SHOW \
		INCLUDE_EXC_TASK \
		INCLUDE_FLOATING_POINT \
		INCLUDE_FORMATTED_IO \
		INCLUDE_GETSERVBYNAME \
		INCLUDE_GNU_INTRINSICS \
		INCLUDE_GTF \
		INCLUDE_GTF_TIMER_START \
		INCLUDE_HASH \
		INCLUDE_HOOKS \
		INCLUDE_HOST_TBL \
		INCLUDE_IFCONFIG \
		INCLUDE_ISR_OBJECTS \
		INCLUDE_INETLIB \
		INCLUDE_IO_SYSTEM \
		INCLUDE_IPATTACH \
		INCLUDE_IPV4 \
		INCLUDE_JOB_TASK \
		INCLUDE_KERNEL \
		INCLUDE_VX_NATIVE_SCHEDULER \
		INCLUDE_LINKBUFPOOL \
		INCLUDE_LOADER \
		INCLUDE_LOGGING \
		INCLUDE_MEMORY_CONFIG \
		INCLUDE_MEM_MGR_BASIC \
		INCLUDE_MEM_MGR_FULL \
		INCLUDE_MEM_SHOW \
		INCLUDE_MIB2_IF \
		INCLUDE_MSG_Q \
		INCLUDE_MSG_Q_CREATE_DELETE \
		INCLUDE_MSG_Q_INFO \
		INCLUDE_MSG_Q_SHOW \
		INCLUDE_MUX \
		INCLUDE_NETBUFLIB \
		INCLUDE_NETBUFPOOL \
		INCLUDE_NETWORK \
		INCLUDE_NET_BOOT \
		INCLUDE_NET_DAEMON \
		INCLUDE_NET_DRV \
		INCLUDE_NET_HOST_SETUP \
		INCLUDE_OBJ_OWNERSHIP \
		INCLUDE_OFFSET_SYMBOLS \
		INCLUDE_PCI_BUS_SHOW \
		INCLUDE_PING \
		INCLUDE_POSIX_CLOCKS \
		INCLUDE_POSIX_DIRLIB \
		INCLUDE_PROTECT_TASK_STACK \
		INCLUDE_REBOOT_HOOKS \
		INCLUDE_REMLIB \
		INCLUDE_ROMFS \
        	INCLUDE_RTP \
		INCLUDE_RTP_APPL_INIT_BOOTLINE \
		INCLUDE_RTP_APPL_USER \
		INCLUDE_RTP_SHOW \
		INCLUDE_RTP_HOOKS \
		INCLUDE_RTP_SHELL_CMD \
		INCLUDE_SELECT \
		INCLUDE_SELECT_SUPPORT \
		INCLUDE_SEM_BINARY \
		INCLUDE_SEM_COUNTING \
		INCLUDE_SEM_MUTEX \
		INCLUDE_SEM_LIB \
		INCLUDE_SEM_DELETE \
		INCLUDE_SEM_BINARY_CREATE \
		INCLUDE_SEM_COUNTING_CREATE \
		INCLUDE_SEM_MUTEX_CREATE \
		INCLUDE_SHARED_DATA \
		INCLUDE_SHARED_DATA_SHOW \
		INCLUDE_SHELL \
		INCLUDE_SHELL_EMACS_MODE \
		INCLUDE_SHELL_INTERP_C \
		INCLUDE_SHELL_INTERP_CMD \
		INCLUDE_SHELL_VI_MODE \
		INCLUDE_SHELL_EMACS_MODE \
		INCLUDE_SHELL_VI_MODE \
		INCLUDE_SHL \
		INCLUDE_SHL_SHOW \
		INCLUDE_SHL_SHELL_CMD \
		INCLUDE_SHOW_ROUTINES \
		INCLUDE_SIGNALS \
		INCLUDE_SIO \
		INCLUDE_SOCKLIB \
                INCLUDE_STARTUP_SCRIPT \
		INCLUDE_STAT_SYM_TBL \
		INCLUDE_STDIO \
		INCLUDE_STRICMP \
		INCLUDE_STANDALONE_SYM_TBL \
		INCLUDE_SYM_TBL \
		INCLUDE_SYM_TBL_SHOW \
		INCLUDE_SYSCLK_INIT \
        	INCLUDE_SYSCTL \
		INCLUDE_SYSHW_INIT \
		INCLUDE_SYS_START \
		INCLUDE_TASK_CREATE_DELETE \
		INCLUDE_TASK_HOOKS \
		INCLUDE_TASK_RESTART \
		INCLUDE_TASK_STACK_NO_EXEC \
		INCLUDE_TASK_VARS \
		INCLUDE_TCPV4 \
		INCLUDE_TIMER_SYS_SHOW \
		INCLUDE_TIMESTAMP \
		INCLUDE_TIMEX \
		INCLUDE_TRIGGERING \
		INCLUDE_TTY_DEV \
		INCLUDE_TYLIB \
		INCLUDE_UDPV4 \
		INCLUDE_UNLOADER \
		INCLUDE_USER_APPL \
		INCLUDE_VXBUS_SHOW \
		INCLUDE_VXEVENTS \
		INCLUDE_WATCHDOGS \
		INCLUDE_WATCHDOGS_CREATE_DELETE \
		INCLUDE_WDB \
		INCLUDE_WDB_BANNER \
		INCLUDE_WDB_BP \
		INCLUDE_WDB_CTXT \
		INCLUDE_WDB_DIRECT_CALL \
		INCLUDE_WDB_DPRINTF \
		INCLUDE_WDB_EVENTPOINTS \
		INCLUDE_WDB_EVENTS \
		INCLUDE_WDB_EXC_NOTIFY \
		INCLUDE_WDB_EXIT_NOTIFY \
		INCLUDE_WDB_FUNC_CALL \
		INCLUDE_WDB_GOPHER \
		INCLUDE_WDB_MEM \
		INCLUDE_WDB_POST_KERNEL_INIT \
		INCLUDE_WDB_REG \
		INCLUDE_WDB_START_NOTIFY \
		INCLUDE_WDB_SYS \
		INCLUDE_WDB_TASK \
		INCLUDE_WDB_TASK_BP \
		INCLUDE_WDB_TASK_HOOKS \
		INCLUDE_WDB_TSFS \
		INCLUDE_WDB_USER_EVENT \
		INCLUDE_WDB_VIO \
		INCLUDE_WDB_VIO_LIB \
                INCLUDE_XDR
#endif /* _WRS_CONFIG_SMP || _WRS_CONFIG_LP64 */
    _CHILDREN	FOLDER_NOT_VISIBLE
    }
