/* sysMpc8540Show.c - "Show" routines for mpc8540. */

/* Copyright 2004 Motorola, Inc. All Rights Reserved */

/*
modification history
--------------------
01i,29aug05,efb Changed core freq variable to sysCoreFreqGet call.
01h,15aug05,efb Changed to calling sysCpuBusSpd().
01g,03aug05,cak Added field to table of registers to indicate whether the
		register is 32- or 8-bit.
01f,29mar05,cak Fixed compiler warnings.
01e,09dec04,cak Add show routine for system memory controller. 
01d,02dec04,scb Fix limit address on ATMU show routine.
01c,01dec04,scb Correct CCSR_IIDR26.
01b,22nov04,scb Fix goof in DdrCltDump (don't dump I2c regs).
01a,16nov04,scb Initial writing - transfer some routines from "sysLib.c".
*/

/*
DESCRIPTION
This file contains show routines for features that are unique to the
mpc8540. PowerQUICC III Integrated Host Processor.
*/

/* includes */

#include "vxWorks.h"
#include "stdio.h"
#include "mpc8540.h"

/* defines */

#define REG_SIZE_8	0
#define REG_SIZE_32	1

#define RINFO	   (1)
#define RSTOP	   (2)
#define REND	   (3)

#define _RDUMP(r,x)  { #r, r, x }
#define _RINFO(s)    { s,  RINFO }
#define _RSTOP	     { "", RSTOP }
#define _REND	     { "", REND }

/* typedefs */

typedef struct
    {
    UINT32 mas0;
    UINT32 mas1;
    UINT32 mas2;
    UINT32 mas3;
    } MAS;

typedef struct
    {
    UINT32 potar;
    UINT32 potear;
    UINT32 powbar;
    UINT32 powar;
    } PARO;

typedef struct
    {
    UINT32 pitar;
    UINT32 piwbar;
    UINT32 piwbear;
    UINT32 piwar;
    } PARI;

typedef struct
    {
    char * label;
    UINT32 regOff;
    UINT32 regSize;
    } MPC8540_REG_DUMP_TBL;

/* globals */

/* locals */

LOCAL MPC8540_REG_DUMP_TBL mpc8540RegDumpTbl [] =

    {

    _RINFO ("Configuration, Control, and Status registers"),

    _RDUMP (CCSR_CCSRBAR, REG_SIZE_32),
    _RDUMP (CCSR_ALTCBAR, REG_SIZE_32),
    _RDUMP (CCSR_ALTCAR, REG_SIZE_32),
    _RDUMP (CCSR_BPTR, REG_SIZE_32),

    _RSTOP,

    _RINFO ("Local Access Window Base and Size Registers"),

    _RDUMP (CCSR_LAWBAR0, REG_SIZE_32),
    _RDUMP (CCSR_LAWAR0, REG_SIZE_32),
    _RDUMP (CCSR_LAWBAR1, REG_SIZE_32),
    _RDUMP (CCSR_LAWAR1, REG_SIZE_32),
    _RDUMP (CCSR_LAWBAR2, REG_SIZE_32),
    _RDUMP (CCSR_LAWAR2, REG_SIZE_32),
    _RDUMP (CCSR_LAWBAR3, REG_SIZE_32),
    _RDUMP (CCSR_LAWAR3, REG_SIZE_32),
    _RDUMP (CCSR_LAWBAR4, REG_SIZE_32),
    _RDUMP (CCSR_LAWAR4, REG_SIZE_32),
    _RDUMP (CCSR_LAWBAR5, REG_SIZE_32),
    _RDUMP (CCSR_LAWAR5, REG_SIZE_32),
    _RDUMP (CCSR_LAWBAR6, REG_SIZE_32),
    _RDUMP (CCSR_LAWAR6, REG_SIZE_32),
    _RDUMP (CCSR_LAWBAR7, REG_SIZE_32),
    _RDUMP (CCSR_LAWAR7, REG_SIZE_32),

    _RSTOP,

    _RINFO ("e500 Coherence Module (ECM) Registers"),

    _RDUMP (CCSR_EEBACR, REG_SIZE_32),
    _RDUMP (CCSR_EEBPCR, REG_SIZE_32),
    _RDUMP (CCSR_EEDR, REG_SIZE_32),
    _RDUMP (CCSR_EEER, REG_SIZE_32),
    _RDUMP (CCSR_EEATR, REG_SIZE_32),
    _RDUMP (CCSR_EEADR, REG_SIZE_32),

    _RSTOP,

    _RINFO ("DDR Memory Controller Memory Map Registers"),

    _RDUMP (CCSR_CS0_BNDS, REG_SIZE_32),
    _RDUMP (CCSR_CS1_BNDS, REG_SIZE_32),
    _RDUMP (CCSR_CS2_BNDS, REG_SIZE_32),
    _RDUMP (CCSR_CS3_BNDS, REG_SIZE_32),
    _RDUMP (CCSR_CS0_CONFIG, REG_SIZE_32),
    _RDUMP (CCSR_CS1_CONFIG, REG_SIZE_32),
    _RDUMP (CCSR_CS2_CONFIG, REG_SIZE_32),
    _RDUMP (CCSR_CS3_CONFIG, REG_SIZE_32),
    _RDUMP (CCSR_TIMING_CFG_1, REG_SIZE_32),
    _RDUMP (CCSR_TIMING_CFG_2, REG_SIZE_32),
    _RDUMP (CCSR_DDR_SDRAM_CFG, REG_SIZE_32),
    _RDUMP (CCSR_DDR_SDRAM_MODE, REG_SIZE_32),
    _RDUMP (CCSR_DDR_SDRAM_INTERVAL, REG_SIZE_32),
    _RDUMP (CCSR_DATA_ERR_INJECT_HI, REG_SIZE_32),
    _RDUMP (CCSR_DATA_ERR_INJECT_LO, REG_SIZE_32),
    _RDUMP (CCSR_ECC_ERR_INJECT, REG_SIZE_32),
    _RDUMP (CCSR_CAPTURE_DATA_HI, REG_SIZE_32),
    _RDUMP (CCSR_CAPTURE_DATA_LO, REG_SIZE_32),
    _RDUMP (CCSR_CAPTURE_ECC, REG_SIZE_32),
    _RDUMP (CCSR_ERR_DETECT, REG_SIZE_32),
    _RDUMP (CCSR_ERR_DISABLE, REG_SIZE_32),
    _RDUMP (CCSR_ERR_INT_EN, REG_SIZE_32),
    _RDUMP (CCSR_CAPTURE_ATTRIBUTES, REG_SIZE_32),
    _RDUMP (CCSR_CAPTURE_ADDRESS, REG_SIZE_32),
    _RDUMP (CCSR_ERR_SBE, REG_SIZE_32),

    _RSTOP,

    _RINFO ("I2C registers"),

    _RDUMP (CCSR_I2CADR, REG_SIZE_8),
    _RDUMP (CCSR_I2CFDR, REG_SIZE_8),
    _RDUMP (CCSR_I2CCR, REG_SIZE_8),
    _RDUMP (CCSR_I2CSR, REG_SIZE_8),
    _RDUMP (CCSR_I2CDR, REG_SIZE_8),
    _RDUMP (CCSR_I2CDFSRR, REG_SIZE_8),

    _RSTOP,

    _RINFO ("DUART Registers"),

    _RDUMP (CCSR_URBR0, REG_SIZE_8),
    _RDUMP (CCSR_UTHR0, REG_SIZE_8),
    _RDUMP (CCSR_UDLB0, REG_SIZE_8),
    _RDUMP (CCSR_UIER0, REG_SIZE_8),
    _RDUMP (CCSR_UDMB0, REG_SIZE_8),
    _RDUMP (CCSR_UIIR0, REG_SIZE_8),
    _RDUMP (CCSR_UFCR0, REG_SIZE_8),
    _RDUMP (CCSR_UAFR0, REG_SIZE_8),
    _RDUMP (CCSR_ULCR0, REG_SIZE_8),
    _RDUMP (CCSR_UMCR0, REG_SIZE_8),
    _RDUMP (CCSR_ULSR0, REG_SIZE_8),
    _RDUMP (CCSR_UMSR0, REG_SIZE_8),
    _RDUMP (CCSR_USCR0, REG_SIZE_8),
    _RDUMP (CCSR_UDSR0, REG_SIZE_8),
    _RDUMP (CCSR_URBR1, REG_SIZE_8),
    _RDUMP (CCSR_UTHR1, REG_SIZE_8),
    _RDUMP (CCSR_UDLB1, REG_SIZE_8),
    _RDUMP (CCSR_UIER1, REG_SIZE_8),
    _RDUMP (CCSR_UDMB1, REG_SIZE_8),
    _RDUMP (CCSR_UIIR1, REG_SIZE_8),
    _RDUMP (CCSR_UFCR1, REG_SIZE_8),
    _RDUMP (CCSR_UAFR1, REG_SIZE_8),
    _RDUMP (CCSR_ULCR1, REG_SIZE_8),
    _RDUMP (CCSR_UMCR1, REG_SIZE_8),
    _RDUMP (CCSR_ULSR1, REG_SIZE_8),
    _RDUMP (CCSR_UMSR1, REG_SIZE_8),
    _RDUMP (CCSR_USCR1, REG_SIZE_8),
    _RDUMP (CCSR_UDSR1, REG_SIZE_8),

    _RSTOP,

    _RINFO ("Local Bus Controller Registers"),

    _RDUMP (CCSR_BR0, REG_SIZE_32),
    _RDUMP (CCSR_BR1, REG_SIZE_32),
    _RDUMP (CCSR_BR2, REG_SIZE_32),
    _RDUMP (CCSR_BR3, REG_SIZE_32),
    _RDUMP (CCSR_BR4, REG_SIZE_32),
    _RDUMP (CCSR_BR5, REG_SIZE_32),
    _RDUMP (CCSR_BR6, REG_SIZE_32),
    _RDUMP (CCSR_BR7, REG_SIZE_32),
    _RDUMP (CCSR_OR0, REG_SIZE_32),
    _RDUMP (CCSR_OR1, REG_SIZE_32),
    _RDUMP (CCSR_OR2, REG_SIZE_32),
    _RDUMP (CCSR_OR3, REG_SIZE_32),
    _RDUMP (CCSR_OR4, REG_SIZE_32),
    _RDUMP (CCSR_OR5, REG_SIZE_32),
    _RDUMP (CCSR_OR6, REG_SIZE_32),
    _RDUMP (CCSR_OR7, REG_SIZE_32),
    _RDUMP (CCSR_MAR, REG_SIZE_32),
    _RDUMP (CCSR_MAMR, REG_SIZE_32),
    _RDUMP (CCSR_MBMR, REG_SIZE_32),
    _RDUMP (CCSR_MCMR, REG_SIZE_32),
    _RDUMP (CCSR_MRTPR, REG_SIZE_32),
    _RDUMP (CCSR_MDR, REG_SIZE_32),
    _RDUMP (CCSR_LSDMR, REG_SIZE_32),
    _RDUMP (CCSR_LURT, REG_SIZE_32),
    _RDUMP (CCSR_LSRT, REG_SIZE_32),
    _RDUMP (CCSR_LTESR, REG_SIZE_32),
    _RDUMP (CCSR_LTEDR, REG_SIZE_32),
    _RDUMP (CCSR_LTEIR, REG_SIZE_32),
    _RDUMP (CCSR_LTEATR, REG_SIZE_32),
    _RDUMP (CCSR_LTEAR, REG_SIZE_32),
    _RDUMP (CCSR_LBCR, REG_SIZE_32),
    _RDUMP (CCSR_LCRR, REG_SIZE_32),

    _RSTOP,

    _RINFO ("PCI/X Configuration Access Registers"),

    _RDUMP (CCSR_CFG_ADDR, REG_SIZE_32),
    _RDUMP (CCSR_CFG_DATA, REG_SIZE_32),
    _RDUMP (CCSR_INT_ACK, REG_SIZE_32),

    _RSTOP,

    _RINFO ("PCI/X ATMU registers - Outbound"),

    _RDUMP (CCSR_POTAR0, REG_SIZE_32),
    _RDUMP (CCSR_POTEAR0, REG_SIZE_32),
    _RDUMP (CCSR_POWBAR0, REG_SIZE_32),
    _RDUMP (CCSR_POWAR0, REG_SIZE_32),
    _RDUMP (CCSR_POTAR1, REG_SIZE_32),
    _RDUMP (CCSR_POTEAR1, REG_SIZE_32),
    _RDUMP (CCSR_POWBAR1, REG_SIZE_32),
    _RDUMP (CCSR_POWAR1, REG_SIZE_32),
    _RDUMP (CCSR_POTAR2, REG_SIZE_32),
    _RDUMP (CCSR_POTEAR2, REG_SIZE_32),
    _RDUMP (CCSR_POWBAR2, REG_SIZE_32),
    _RDUMP (CCSR_POWAR2, REG_SIZE_32),
    _RDUMP (CCSR_POTAR3, REG_SIZE_32),
    _RDUMP (CCSR_POTEAR3, REG_SIZE_32),
    _RDUMP (CCSR_POWBAR3, REG_SIZE_32),
    _RDUMP (CCSR_POWAR3, REG_SIZE_32),
    _RDUMP (CCSR_POTAR4, REG_SIZE_32),
    _RDUMP (CCSR_POTEAR4, REG_SIZE_32),
    _RDUMP (CCSR_POWBAR4, REG_SIZE_32),
    _RDUMP (CCSR_POWAR4, REG_SIZE_32),

    _RINFO ("PCI/X ATMU registers - Inbound"),

    _RDUMP (CCSR_PITAR3, REG_SIZE_32),
    _RDUMP (CCSR_PIWBAR3, REG_SIZE_32),
    _RDUMP (CCSR_PIWBEAR3, REG_SIZE_32),
    _RDUMP (CCSR_PIWAR3, REG_SIZE_32),
    _RDUMP (CCSR_PITAR2, REG_SIZE_32),
    _RDUMP (CCSR_PIWBAR2, REG_SIZE_32),
    _RDUMP (CCSR_PIWBEAR2, REG_SIZE_32),
    _RDUMP (CCSR_PIWAR2, REG_SIZE_32),
    _RDUMP (CCSR_PITAR1, REG_SIZE_32),
    _RDUMP (CCSR_PIWBAR1, REG_SIZE_32),
    _RDUMP (CCSR_PIWAR1, REG_SIZE_32),

    _RSTOP,

    _RINFO ("PCI/X Error Management Registers"),

    _RDUMP (CCSR_ERR_DR, REG_SIZE_32),
    _RDUMP (CCSR_ERR_CAP_DR, REG_SIZE_32),
    _RDUMP (CCSR_ERR_EN, REG_SIZE_32),
    _RDUMP (CCSR_ERR_ATTRIB, REG_SIZE_32),
    _RDUMP (CCSR_ERR_ADDR, REG_SIZE_32),
    _RDUMP (CCSR_ERR_EXT_ADDR, REG_SIZE_32),
    _RDUMP (CCSR_ERR_DL, REG_SIZE_32),
    _RDUMP (CCSR_ERR_DH, REG_SIZE_32),
    _RDUMP (CCSR_GAS_TIMR, REG_SIZE_32),
    _RDUMP (CCSR_PCIX_TIMR, REG_SIZE_32),

    _RSTOP,

    _RINFO ("L2/SRAM Memory - Mapped Configuration Registers"),

    _RDUMP (CCSR_L2CTL, REG_SIZE_32),
    _RDUMP (CCSR_L2CEWAR0, REG_SIZE_32),
    _RDUMP (CCSR_L2CEWCR0, REG_SIZE_32),
    _RDUMP (CCSR_L2CEWAR1, REG_SIZE_32),
    _RDUMP (CCSR_L2CEWCR1, REG_SIZE_32),
    _RDUMP (CCSR_L2CEWAR2, REG_SIZE_32),
    _RDUMP (CCSR_L2CEWCR2, REG_SIZE_32),
    _RDUMP (CCSR_L2CEWAR3, REG_SIZE_32),
    _RDUMP (CCSR_L2CEWCR3, REG_SIZE_32),
    _RDUMP (CCSR_L2SRBAR0, REG_SIZE_32),
    _RDUMP (CCSR_L2SRBAR1, REG_SIZE_32),
    _RDUMP (CCSR_L2ERRINJHI, REG_SIZE_32),
    _RDUMP (CCSR_L2ERRINJLO, REG_SIZE_32),
    _RDUMP (CCSR_L2ERRINJCTL, REG_SIZE_32),
    _RDUMP (CCSR_L2CAPTDATAHI, REG_SIZE_32),
    _RDUMP (CCSR_L2CAPTDATALO, REG_SIZE_32),
    _RDUMP (CCSR_L2CAPTECC, REG_SIZE_32),
    _RDUMP (CCSR_L2ERRDET, REG_SIZE_32),
    _RDUMP (CCSR_L2ERRDIS, REG_SIZE_32),
    _RDUMP (CCSR_L2ERRINTEN, REG_SIZE_32),
    _RDUMP (CCSR_L2ERRATTR, REG_SIZE_32),
    _RDUMP (CCSR_L2ERRADDR, REG_SIZE_32),
    _RDUMP (CCSR_L2ERRCTL, REG_SIZE_32),

    _RSTOP,

    _RINFO ("DMA Registers"),

    _RDUMP (CCSR_MR0, REG_SIZE_32),
    _RDUMP (CCSR_SR0, REG_SIZE_32),
    _RDUMP (CCSR_CLNDAR0, REG_SIZE_32),
    _RDUMP (CCSR_SATR0, REG_SIZE_32),
    _RDUMP (CCSR_SAR0, REG_SIZE_32),
    _RDUMP (CCSR_DATR0, REG_SIZE_32),
    _RDUMP (CCSR_DAR0, REG_SIZE_32),
    _RDUMP (CCSR_BCR0, REG_SIZE_32),
    _RDUMP (CCSR_NLNDAR0, REG_SIZE_32),
    _RDUMP (CCSR_CLSDAR0, REG_SIZE_32),
    _RDUMP (CCSR_NLSDAR0, REG_SIZE_32),
    _RDUMP (CCSR_SSR0, REG_SIZE_32),
    _RDUMP (CCSR_DSR0, REG_SIZE_32),
    _RDUMP (CCSR_MR1, REG_SIZE_32),
    _RDUMP (CCSR_SR1, REG_SIZE_32),
    _RDUMP (CCSR_CLNDAR1, REG_SIZE_32),
    _RDUMP (CCSR_SATR1, REG_SIZE_32),
    _RDUMP (CCSR_SAR1, REG_SIZE_32),
    _RDUMP (CCSR_DATR1, REG_SIZE_32),
    _RDUMP (CCSR_DAR1, REG_SIZE_32),
    _RDUMP (CCSR_BCR1, REG_SIZE_32),
    _RDUMP (CCSR_NLNDAR1, REG_SIZE_32),
    _RDUMP (CCSR_CLSDAR1, REG_SIZE_32),
    _RDUMP (CCSR_NLSDAR1, REG_SIZE_32),
    _RDUMP (CCSR_SSR1, REG_SIZE_32),
    _RDUMP (CCSR_DSR1, REG_SIZE_32),
    _RDUMP (CCSR_MR2, REG_SIZE_32),
    _RDUMP (CCSR_SR2, REG_SIZE_32),
    _RDUMP (CCSR_CLNDAR2, REG_SIZE_32),
    _RDUMP (CCSR_SATR2, REG_SIZE_32),
    _RDUMP (CCSR_SAR2, REG_SIZE_32),
    _RDUMP (CCSR_DATR2, REG_SIZE_32),
    _RDUMP (CCSR_DAR2, REG_SIZE_32),
    _RDUMP (CCSR_BCR2, REG_SIZE_32),
    _RDUMP (CCSR_NLNDAR2, REG_SIZE_32),
    _RDUMP (CCSR_CLSDAR2, REG_SIZE_32),
    _RDUMP (CCSR_NLSDAR2, REG_SIZE_32),
    _RDUMP (CCSR_SSR2, REG_SIZE_32),
    _RDUMP (CCSR_DSR2, REG_SIZE_32),
    _RDUMP (CCSR_MR3, REG_SIZE_32),
    _RDUMP (CCSR_SR3, REG_SIZE_32),
    _RDUMP (CCSR_CLNDAR3, REG_SIZE_32),
    _RDUMP (CCSR_SATR3, REG_SIZE_32),
    _RDUMP (CCSR_SAR3, REG_SIZE_32),
    _RDUMP (CCSR_DATR3, REG_SIZE_32),
    _RDUMP (CCSR_DAR3, REG_SIZE_32),
    _RDUMP (CCSR_BCR3, REG_SIZE_32),
    _RDUMP (CCSR_NLNDAR3, REG_SIZE_32),
    _RDUMP (CCSR_CLSDAR3, REG_SIZE_32),
    _RDUMP (CCSR_NLSDAR3, REG_SIZE_32),
    _RDUMP (CCSR_SSR3, REG_SIZE_32),
    _RDUMP (CCSR_DSR3, REG_SIZE_32),
    _RDUMP (CCSR_DGSR, REG_SIZE_32),

    _RSTOP,

    _RINFO ("TSEC1 General Control And Status Registers"),

    _RDUMP (CCSR_TSEC1_IEVENT, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_IMASK, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_EDIS, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_ECNTRL, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_MINFLR, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_PTV, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_DMACTRL, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_TBIPA, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_FIFO_PAUSE_CTRL, REG_SIZE_32),

    _RINFO ("TSEC1 FIFO Control and Status Registers"),

    _RDUMP (CCSR_TSEC1_FIFO_TX_THR, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_FIFO_TX_STARVE, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_FIFO_TX_STARVE_SHUTOFF, REG_SIZE_32),

    _RINFO ("TSEC1 Transmit Control and Status Registers"),

    _RDUMP (CCSR_TSEC1_TCTRL, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_TSTAT, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_TBDLEN, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_TXIC, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_CTBPTR, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_TBPTR, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_TBASE, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_OSTBD, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_OSTBDP, REG_SIZE_32),

    _RINFO ("TSEC1 Receive Control and Status Registers"),

    _RDUMP (CCSR_TSEC1_RCTRL, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_RSTAT, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_RBDLEN, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_RXIC, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_CRBPTR, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_MRBLR, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_RBPTR, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_RBASE, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_MACCFG1, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_MACCFG2, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_IPGIFG, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_HAFDUP, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_MAXFRM, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_MIIMCFG, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_MIIMCOM, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_MIIMADD, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_MIIMCON, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_MIIMSTAT, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_MIIMIND, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_IFSTAT, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_MACSTNADDR1, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_MACSTNADDR2, REG_SIZE_32),

    _RINFO ("TSEC1 Transmit and Receive Counters"),

    _RDUMP (CCSR_TSEC1_TR64, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_TR127, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_TR255, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_TR511, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_TR1K, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_TRMAX, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_TRMGV, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_RBYT, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_RPKT, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_RFCS, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_RMCA, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_RBCA, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_RXCF, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_RXPF, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_RXUO, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_RALN, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_RFLR, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_RCDE, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_RCSE, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_RUND, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_ROVR, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_RFRG, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_RJBR, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_RDRP, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_TBYT, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_TPKT, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_TMCA, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_TBCA, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_TXPF, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_TDFR, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_TEDF, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_TSCL, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_TMCL, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_TLCL, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_TXCL, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_TNCL, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_TDRP, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_TJBR, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_TFCS, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_TXCF, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_TOVR, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_TUND, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_TFRG, REG_SIZE_32),

    _RINFO ("TSEC1 General Registers"),

    _RDUMP (CCSR_TSEC1_CAR1, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_CAR2, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_CAM1, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_CAM2, REG_SIZE_32),

    _RINFO ("TSEC1 Hash Function Registers"),

    _RDUMP (CCSR_TSEC1_IADDR0, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_IADDR1, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_IADDR2, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_IADDR3, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_IADDR4, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_IADDR5, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_IADDR6, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_IADDR7, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_GADDR0, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_GADDR1, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_GADDR2, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_GADDR3, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_GADDR4, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_GADDR5, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_GADDR6, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_GADDR7, REG_SIZE_32),

    _RINFO ("TSEC1 Attribute Registers"),

    _RDUMP (CCSR_TSEC1_ATTR, REG_SIZE_32),
    _RDUMP (CCSR_TSEC1_ATTRELI, REG_SIZE_32),

    _RSTOP,

    _RINFO ("TSEC2 General Control And Status Registers"),

    _RDUMP (CCSR_TSEC2_IEVENT, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_IMASK, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_EDIS, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_ECNTRL, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_MINFLR, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_PTV, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_DMACTRL, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_TBIPA, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_FIFO_PAUSE_CTRL, REG_SIZE_32),

    _RINFO ("TSEC2 FIFO Control and Status Registers"),

    _RDUMP (CCSR_TSEC2_FIFO_TX_THR, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_FIFO_TX_STARVE, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_FIFO_TX_STARVE_SHUTOFF, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_TCTRL, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_TSTAT, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_TBDLEN, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_TXIC, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_CTBPTR, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_TBPTR, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_TBASE, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_OSTBD, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_OSTBDP, REG_SIZE_32),

    _RINFO ("TSEC2 Receive Control and Status Registers"),

    _RDUMP (CCSR_TSEC2_RCTRL, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_RSTAT, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_RBDLEN, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_RXIC, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_CRBPTR, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_MRBLR, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_RBPTR, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_RBASE, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_MACCFG1, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_MACCFG2, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_IPGIFG, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_HAFDUP, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_MAXFRM, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_MIIMCFG, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_MIIMCOM, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_MIIMADD, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_MIIMCON, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_MIIMSTAT, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_MIIMIND, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_IFSTAT, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_MACSTNADDR1, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_MACSTNADDR2, REG_SIZE_32),

    _RINFO ("TSEC2 Transmit and Receive Counters"),

    _RDUMP (CCSR_TSEC2_TR64, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_TR127, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_TR255, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_TR511, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_TR1K, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_TRMAX, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_TRMGV, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_RBYT, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_RPKT, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_RFCS, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_RMCA, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_RBCA, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_RXCF, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_RXPF, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_RXUO, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_RALN, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_RFLR, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_RCDE, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_RCSE, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_RUND, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_ROVR, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_RFRG, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_RJBR, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_RDRP, REG_SIZE_32),

    _RINFO ("TSEC2 Transmit Counters"),

    _RDUMP (CCSR_TSEC2_TBYT, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_TPKT, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_TMCA, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_TBCA, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_TXPF, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_TDFR, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_TEDF, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_TSCL, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_TMCL, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_TLCL, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_TXCL, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_TNCL, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_TDRP, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_TJBR, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_TFCS, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_TXCF, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_TOVR, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_TUND, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_TFRG, REG_SIZE_32),

    _RINFO ("TSEC2 General Registers"),

    _RDUMP (CCSR_TSEC2_CAR1, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_CAR2, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_CAM1, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_CAM2, REG_SIZE_32),

    _RINFO ("TSEC2 Hash Function Registers"),
    
    _RDUMP (CCSR_TSEC2_IADDR0, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_IADDR1, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_IADDR2, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_IADDR3, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_IADDR4, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_IADDR5, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_IADDR6, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_IADDR7, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_GADDR0, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_GADDR1, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_GADDR2, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_GADDR3, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_GADDR4, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_GADDR5, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_GADDR6, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_GADDR7, REG_SIZE_32),

    _RINFO ("TSEC2 Attribute Registers"),

    _RDUMP (CCSR_TSEC2_ATTR, REG_SIZE_32),
    _RDUMP (CCSR_TSEC2_ATTRELI, REG_SIZE_32),

    _RSTOP,

    _RINFO ("Fast Ethernet Controller (FEC) Registers"),

    _RDUMP (CCSR_FEC_IEVENT, REG_SIZE_32),
    _RDUMP (CCSR_FEC_IMASK, REG_SIZE_32),
    _RDUMP (CCSR_FEC_EDIS, REG_SIZE_32),
    _RDUMP (CCSR_FEC_MINFLR, REG_SIZE_32),
    _RDUMP (CCSR_FEC_PTV, REG_SIZE_32),
    _RDUMP (CCSR_FEC_DMACTRL, REG_SIZE_32),
    _RDUMP (CCSR_FIFO_PAUSE_CTRL, REG_SIZE_32),

    _RINFO ("FEC FIFO Control and Status Registers"),

    _RDUMP (CCSR_FIFO_TX_THR, REG_SIZE_32),
    _RDUMP (CCSR_FIFO_TX_STARVE, REG_SIZE_32),
    _RDUMP (CCSR_FIFO_TX_STARVE_SHUTOFF, REG_SIZE_32),

    _RINFO ("FEC Transmit Control and Status Registers"),

    _RDUMP (CCSR_TCTRL, REG_SIZE_32),
    _RDUMP (CCSR_TSTAT, REG_SIZE_32),
    _RDUMP (CCSR_TBDLEN, REG_SIZE_32),
    _RDUMP (CCSR_CTBPTR, REG_SIZE_32),
    _RDUMP (CCSR_TBPTR, REG_SIZE_32),
    _RDUMP (CCSR_TBASE, REG_SIZE_32),
    _RDUMP (CCSR_OSTBD, REG_SIZE_32),
    _RDUMP (CCSR_OSTBDP, REG_SIZE_32),

    _RINFO ("FEC Receive Control and Status Registers"),

    _RDUMP (CCSR_RCTRL, REG_SIZE_32),
    _RDUMP (CCSR_RSTAT, REG_SIZE_32),
    _RDUMP (CCSR_RBDLEN, REG_SIZE_32),
    _RDUMP (CCSR_CRBPTR, REG_SIZE_32),
    _RDUMP (CCSR_MRBLR, REG_SIZE_32),
    _RDUMP (CCSR_RBPTR, REG_SIZE_32),
    _RDUMP (CCSR_RBASE, REG_SIZE_32),

    _RINFO ("FEC MAC Registers"),

    _RDUMP (CCSR_MACCFG1, REG_SIZE_32),
    _RDUMP (CCSR_MACCFG2, REG_SIZE_32),
    _RDUMP (CCSR_IPGIFG, REG_SIZE_32),
    _RDUMP (CCSR_HAFDUP, REG_SIZE_32),
    _RDUMP (CCSR_MAXFRM, REG_SIZE_32),
    _RDUMP (CCSR_IFSTAT, REG_SIZE_32),
    _RDUMP (CCSR_MACSTNADDR1, REG_SIZE_32),
    _RDUMP (CCSR_MACSTNADDR2, REG_SIZE_32),

    _RINFO ("FEC Hash Function Registers"),

    _RDUMP (CCSR_IADDR0, REG_SIZE_32),
    _RDUMP (CCSR_IADDR1, REG_SIZE_32),
    _RDUMP (CCSR_IADDR2, REG_SIZE_32),
    _RDUMP (CCSR_IADDR3, REG_SIZE_32),
    _RDUMP (CCSR_IADDR4, REG_SIZE_32),
    _RDUMP (CCSR_IADDR5, REG_SIZE_32),
    _RDUMP (CCSR_IADDR6, REG_SIZE_32),
    _RDUMP (CCSR_IADDR7, REG_SIZE_32),
    _RDUMP (CCSR_GADDR0, REG_SIZE_32),
    _RDUMP (CCSR_GADDR1, REG_SIZE_32),
    _RDUMP (CCSR_GADDR2, REG_SIZE_32),
    _RDUMP (CCSR_GADDR3, REG_SIZE_32),
    _RDUMP (CCSR_GADDR4, REG_SIZE_32),
    _RDUMP (CCSR_GADDR5, REG_SIZE_32),
    _RDUMP (CCSR_GADDR6, REG_SIZE_32),
    _RDUMP (CCSR_GADDR7, REG_SIZE_32),

    _RINFO ("FEC  Attribute Registers"),

    _RDUMP (CCSR_ATTR, REG_SIZE_32),
    _RDUMP (CCSR_ATTRELI, REG_SIZE_32),

    _RSTOP,

    _RINFO ("PIC - Global Registers"),

    _RDUMP (CCSR_GLBL_IPIDR0, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_IPIDR1, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_IPIDR2, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_IPIDR3, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_CTPR, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_WHOAMI, REG_SIZE_32),

#if 0	/* Should only be accessed by the interrupt controller */
    _RDUMP (CCSR_GLBL_IACK, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_EOI, REG_SIZE_32),
#endif

    _RDUMP (CCSR_GLBL_FRR, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_GCR, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_VIR, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_PIR, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_IPIVPR0, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_IPIVPR1, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_IPIVPR2, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_IPIVPR3, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_SVR, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_TFRR, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_GTCCR0, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_GTBCR0, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_GTVPR0, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_GTDR0, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_GTCCR1, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_GTBCR1, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_GTVPR1, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_GTDR1, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_GTCCR2, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_GTBCR2, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_GTVPR2, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_GTDR2, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_GTCCR3, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_GTBCR3, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_GTVPR3, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_GTDR3, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_TCR, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_IRQSR0, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_IRQSR1, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_CISR0, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_CISR1, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_PM0MR0, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_PM0MR1, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_PM1MR0, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_PM1MR1, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_PM2MR0, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_PM2MR1, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_PM3MR0, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_PM3MR1, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_MSGR0, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_MSGR1, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_MSGR2, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_MSGR3, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_MER, REG_SIZE_32),
    _RDUMP (CCSR_GLBL_MSR, REG_SIZE_32),

    _RSTOP,

    _RINFO ("PIC - Internal Source Configuration Registers"),

    _RDUMP (CCSR_EIVPR0, REG_SIZE_32),
    _RDUMP (CCSR_EIDR0, REG_SIZE_32),
    _RDUMP (CCSR_EIVPR1, REG_SIZE_32),
    _RDUMP (CCSR_EIDR1, REG_SIZE_32),
    _RDUMP (CCSR_EIVPR2, REG_SIZE_32),
    _RDUMP (CCSR_EIDR2, REG_SIZE_32),
    _RDUMP (CCSR_EIVPR3, REG_SIZE_32),
    _RDUMP (CCSR_EIDR3, REG_SIZE_32),
    _RDUMP (CCSR_EIVPR4, REG_SIZE_32),
    _RDUMP (CCSR_EIDR4, REG_SIZE_32),
    _RDUMP (CCSR_EIVPR5, REG_SIZE_32),
    _RDUMP (CCSR_EIDR5, REG_SIZE_32),
    _RDUMP (CCSR_EIVPR6, REG_SIZE_32),
    _RDUMP (CCSR_EIDR6, REG_SIZE_32),
    _RDUMP (CCSR_EIVPR7, REG_SIZE_32),
    _RDUMP (CCSR_EIDR7, REG_SIZE_32),
    _RDUMP (CCSR_EIVPR8, REG_SIZE_32),
    _RDUMP (CCSR_EIDR8, REG_SIZE_32),
    _RDUMP (CCSR_EIVPR9, REG_SIZE_32),
    _RDUMP (CCSR_EIDR9, REG_SIZE_32),
    _RDUMP (CCSR_EIVPR10, REG_SIZE_32),
    _RDUMP (CCSR_EIDR10, REG_SIZE_32),
    _RDUMP (CCSR_EIVPR11, REG_SIZE_32),
    _RDUMP (CCSR_EIDR11, REG_SIZE_32),
    _RDUMP (CCSR_IIVPR0, REG_SIZE_32),
    _RDUMP (CCSR_IIDR0, REG_SIZE_32),
    _RDUMP (CCSR_IIVPR1, REG_SIZE_32),
    _RDUMP (CCSR_IIDR1, REG_SIZE_32),
    _RDUMP (CCSR_IIVPR2, REG_SIZE_32),
    _RDUMP (CCSR_IIDR2, REG_SIZE_32),
    _RDUMP (CCSR_IIVPR3, REG_SIZE_32),
    _RDUMP (CCSR_IIDR3, REG_SIZE_32),
    _RDUMP (CCSR_IIVPR4, REG_SIZE_32),
    _RDUMP (CCSR_IIDR4, REG_SIZE_32),
    _RDUMP (CCSR_IIVPR5, REG_SIZE_32),
    _RDUMP (CCSR_IIDR5, REG_SIZE_32),
    _RDUMP (CCSR_IIVPR6, REG_SIZE_32),
    _RDUMP (CCSR_IIDR6, REG_SIZE_32),
    _RDUMP (CCSR_IIVPR7, REG_SIZE_32),
    _RDUMP (CCSR_IIDR7, REG_SIZE_32),
    _RDUMP (CCSR_IIVPR8, REG_SIZE_32),
    _RDUMP (CCSR_IIDR8, REG_SIZE_32),
    _RDUMP (CCSR_IIVPR9, REG_SIZE_32),
    _RDUMP (CCSR_IIDR9, REG_SIZE_32),
    _RDUMP (CCSR_IIVPR10, REG_SIZE_32),
    _RDUMP (CCSR_IIDR10, REG_SIZE_32),
    _RDUMP (CCSR_IIVPR11, REG_SIZE_32),
    _RDUMP (CCSR_IIDR11, REG_SIZE_32),
    _RDUMP (CCSR_IIVPR12, REG_SIZE_32),
    _RDUMP (CCSR_IIDR12, REG_SIZE_32),
    _RDUMP (CCSR_IIVPR13, REG_SIZE_32),
    _RDUMP (CCSR_IIDR13, REG_SIZE_32),
    _RDUMP (CCSR_IIVPR14, REG_SIZE_32),
    _RDUMP (CCSR_IIDR14, REG_SIZE_32),
    _RDUMP (CCSR_IIVPR15, REG_SIZE_32),
    _RDUMP (CCSR_IIDR15, REG_SIZE_32),
    _RDUMP (CCSR_IIVPR16, REG_SIZE_32),
    _RDUMP (CCSR_IIDR16, REG_SIZE_32),
    _RDUMP (CCSR_IIVPR17, REG_SIZE_32),
    _RDUMP (CCSR_IIDR17, REG_SIZE_32),
    _RDUMP (CCSR_IIVPR18, REG_SIZE_32),
    _RDUMP (CCSR_IIDR18, REG_SIZE_32),
    _RDUMP (CCSR_IIVPR19, REG_SIZE_32),
    _RDUMP (CCSR_IIDR19, REG_SIZE_32),
    _RDUMP (CCSR_IIVPR20, REG_SIZE_32),
    _RDUMP (CCSR_IIDR20, REG_SIZE_32),
    _RDUMP (CCSR_IIVPR21, REG_SIZE_32),
    _RDUMP (CCSR_IIDR21, REG_SIZE_32),
    _RDUMP (CCSR_IIVPR22, REG_SIZE_32),
    _RDUMP (CCSR_IIDR22, REG_SIZE_32),
    _RDUMP (CCSR_IIVPR23, REG_SIZE_32),
    _RDUMP (CCSR_IIDR23, REG_SIZE_32),
    _RDUMP (CCSR_IIVPR24, REG_SIZE_32),
    _RDUMP (CCSR_IIDR24, REG_SIZE_32),
    _RDUMP (CCSR_IIVPR25, REG_SIZE_32),
    _RDUMP (CCSR_IIDR25, REG_SIZE_32),
    _RDUMP (CCSR_IIVPR26, REG_SIZE_32),
    _RDUMP (CCSR_IIDR26, REG_SIZE_32),
    _RDUMP (CCSR_IIVPR27, REG_SIZE_32),
    _RDUMP (CCSR_IIDR27, REG_SIZE_32),
    _RDUMP (CCSR_IIVPR28, REG_SIZE_32),
    _RDUMP (CCSR_IIDR28, REG_SIZE_32),
    _RDUMP (CCSR_IIVPR29, REG_SIZE_32),
    _RDUMP (CCSR_IIDR29, REG_SIZE_32),
    _RDUMP (CCSR_IIVPR30, REG_SIZE_32),
    _RDUMP (CCSR_IIDR30, REG_SIZE_32),
    _RDUMP (CCSR_IIVPR31, REG_SIZE_32),
    _RDUMP (CCSR_IIDR31, REG_SIZE_32),
    _RDUMP (CCSR_MIVPR0, REG_SIZE_32),
    _RDUMP (CCSR_MIDR0, REG_SIZE_32),
    _RDUMP (CCSR_MIVPR1, REG_SIZE_32),
    _RDUMP (CCSR_MIDR1, REG_SIZE_32),
    _RDUMP (CCSR_MIVPR2, REG_SIZE_32),
    _RDUMP (CCSR_MIDR2, REG_SIZE_32),
    _RDUMP (CCSR_MIVPR3, REG_SIZE_32),
    _RDUMP (CCSR_MIDR3, REG_SIZE_32),

    _RSTOP,

    _RINFO ("PIC - Per-CPU Registers"),

    _RDUMP (CCSR_CPU_IPIDR0, REG_SIZE_32),
    _RDUMP (CCSR_CPU_IPIDR1, REG_SIZE_32),
    _RDUMP (CCSR_CPU_IPIDR2, REG_SIZE_32),
    _RDUMP (CCSR_CPU_IPIDR3, REG_SIZE_32),
    _RDUMP (CCSR_CPU_CTPR0, REG_SIZE_32),
    _RDUMP (CCSR_CPU_WHOAMI0, REG_SIZE_32),
    _RDUMP (CCSR_CPU_IACK0, REG_SIZE_32),
    _RDUMP (CCSR_CPU_EOI0, REG_SIZE_32),

    _RSTOP,

    _RINFO ("RapidIO Architectural Registers"),

#if 0	/* Accessing DIDCAR causes board to hang */
    _RDUMP (CCSR_RIO_DIDCAR, REG_SIZE_32),
#endif
    _RDUMP (CCSR_RIO_DICAR, REG_SIZE_32),
    _RDUMP (CCSR_RIO_AIDCAR, REG_SIZE_32),
    _RDUMP (CCSR_RIO_AICAR, REG_SIZE_32),
    _RDUMP (CCSR_RIO_PEFCAR, REG_SIZE_32),
    _RDUMP (CCSR_RIO_SPICAR, REG_SIZE_32),
    _RDUMP (CCSR_RIO_SOCAR, REG_SIZE_32),
    _RDUMP (CCSR_RIO_DOCAR, REG_SIZE_32),
    _RDUMP (CCSR_RIO_MSR, REG_SIZE_32),
    _RDUMP (CCSR_RIO_PWDCSR, REG_SIZE_32),
    _RDUMP (CCSR_RIO_PELLCCSR, REG_SIZE_32),
    _RDUMP (CCSR_RIO_LCSBA1CSR, REG_SIZE_32),
    _RDUMP (CCSR_RIO_BDIDCSR, REG_SIZE_32),
    _RDUMP (CCSR_RIO_HBDIDLCSR, REG_SIZE_32),
    _RDUMP (CCSR_RIO_CTCSR, REG_SIZE_32),
    _RDUMP (CCSR_RIO_PMBH0CSR, REG_SIZE_32),
    _RDUMP (CCSR_RIO_PLTOCCSR, REG_SIZE_32),
    _RDUMP (CCSR_RIO_PRTOCCSR, REG_SIZE_32),
    _RDUMP (CCSR_RIO_PGCCSR, REG_SIZE_32),
    _RDUMP (CCSR_RIO_PLMREQCSR, REG_SIZE_32),
    _RDUMP (CCSR_RIO_PLMRESPCSR, REG_SIZE_32),
    _RDUMP (CCSR_RIO_PLASCSR, REG_SIZE_32),
    _RDUMP (CCSR_RIO_PESCSR, REG_SIZE_32),
    _RDUMP (CCSR_RIO_PCCSR, REG_SIZE_32),

    _RINFO ("RapidIO Implementation Registers"),

    _RDUMP (CCSR_CR, REG_SIZE_32),
    _RDUMP (CCSR_PCR, REG_SIZE_32),
    _RDUMP (CCSR_PEIR, REG_SIZE_32),

    _RINFO ("RapidIO ATMU Registers"),

    _RDUMP (CCSR_ROWTAR0, REG_SIZE_32),
    _RDUMP (CCSR_ROWAR0, REG_SIZE_32),
    _RDUMP (CCSR_ROWTAR1, REG_SIZE_32),
    _RDUMP (CCSR_ROWBAR1, REG_SIZE_32),
    _RDUMP (CCSR_ROWAR1, REG_SIZE_32),
    _RDUMP (CCSR_ROWTAR2, REG_SIZE_32),
    _RDUMP (CCSR_ROWBAR2, REG_SIZE_32),
    _RDUMP (CCSR_ROWAR2, REG_SIZE_32),
    _RDUMP (CCSR_ROWTAR3, REG_SIZE_32),
    _RDUMP (CCSR_ROWBAR3, REG_SIZE_32),
    _RDUMP (CCSR_ROWAR3, REG_SIZE_32),
    _RDUMP (CCSR_ROWTAR4, REG_SIZE_32),
    _RDUMP (CCSR_ROWBAR4, REG_SIZE_32),
    _RDUMP (CCSR_ROWAR4, REG_SIZE_32),
    _RDUMP (CCSR_ROWTAR5, REG_SIZE_32),
    _RDUMP (CCSR_ROWBAR5, REG_SIZE_32),
    _RDUMP (CCSR_ROWAR5, REG_SIZE_32),
    _RDUMP (CCSR_ROWTAR6, REG_SIZE_32),
    _RDUMP (CCSR_ROWBAR6, REG_SIZE_32),
    _RDUMP (CCSR_ROWAR6, REG_SIZE_32),
    _RDUMP (CCSR_ROWTAR7, REG_SIZE_32),
    _RDUMP (CCSR_ROWBAR7, REG_SIZE_32),
    _RDUMP (CCSR_ROWAR7, REG_SIZE_32),
    _RDUMP (CCSR_ROWTAR8, REG_SIZE_32),
    _RDUMP (CCSR_ROWBAR8, REG_SIZE_32),
    _RDUMP (CCSR_ROWAR8, REG_SIZE_32),
    _RDUMP (CCSR_RIWTAR4, REG_SIZE_32),
    _RDUMP (CCSR_RIWBAR4, REG_SIZE_32),
    _RDUMP (CCSR_RIWAR4, REG_SIZE_32),
    _RDUMP (CCSR_RIWTAR3, REG_SIZE_32),
    _RDUMP (CCSR_RIWBAR3, REG_SIZE_32),
    _RDUMP (CCSR_RIWAR3, REG_SIZE_32),
    _RDUMP (CCSR_RIWTAR2, REG_SIZE_32),
    _RDUMP (CCSR_RIWBAR2, REG_SIZE_32),
    _RDUMP (CCSR_RIWAR2, REG_SIZE_32),
    _RDUMP (CCSR_RIWTAR1, REG_SIZE_32),
    _RDUMP (CCSR_RIWBAR1, REG_SIZE_32),
    _RDUMP (CCSR_RIWAR1, REG_SIZE_32),
    _RDUMP (CCSR_RIWTAR0, REG_SIZE_32),
    _RDUMP (CCSR_RIWAR0, REG_SIZE_32),

    _RINFO ("RapidIO Error Management Registers"),

    _RDUMP (CCSR_PNFEDR, REG_SIZE_32),
    _RDUMP (CCSR_PNFEDIR, REG_SIZE_32),
    _RDUMP (CCSR_PNFEIER, REG_SIZE_32),
    _RDUMP (CCSR_PECSR, REG_SIZE_32),
    _RDUMP (CCSR_EPCR0, REG_SIZE_32),
    _RDUMP (CCSR_EPCR1, REG_SIZE_32),
    _RDUMP (CCSR_EPCR2, REG_SIZE_32),
    _RDUMP (CCSR_PREDR, REG_SIZE_32),
    _RDUMP (CCSR_PERTR, REG_SIZE_32),
    _RDUMP (CCSR_PRTR, REG_SIZE_32),

    _RINFO ("RapidIO Outbound Message Registers"),

    _RDUMP (CCSR_OMR, REG_SIZE_32),
    _RDUMP (CCSR_OSR, REG_SIZE_32),
    _RDUMP (CCSR_ODQDPAR, REG_SIZE_32),
    _RDUMP (CCSR_OSAR, REG_SIZE_32),
    _RDUMP (CCSR_ODPR, REG_SIZE_32),
    _RDUMP (CCSR_ODATR, REG_SIZE_32),
    _RDUMP (CCSR_ODCR, REG_SIZE_32),
    _RDUMP (CCSR_ODQEPAR, REG_SIZE_32),

    _RINFO ("RapidIO Inbound Message Registers"),

    _RDUMP (CCSR_IMR, REG_SIZE_32),
    _RDUMP (CCSR_ISR, REG_SIZE_32),
    _RDUMP (CCSR_IFQDPAR, REG_SIZE_32),
    _RDUMP (CCSR_IFQEPAR, REG_SIZE_32),

    _RINFO ("RapidIO Doorbell Registers"),

    _RDUMP (CCSR_DMR, REG_SIZE_32),
    _RDUMP (CCSR_DSR, REG_SIZE_32),
    _RDUMP (CCSR_DQDPAR, REG_SIZE_32),
    _RDUMP (CCSR_DQEPAR, REG_SIZE_32),

    _RINFO ("RapidIO Port-Write Registers"),

    _RDUMP (CCSR_PWMR, REG_SIZE_32),
    _RDUMP (CCSR_PWSR, REG_SIZE_32),
    _RDUMP (CCSR_PWQBAR, REG_SIZE_32),

    _RSTOP,

    _RINFO ("Global Utilities: Power-on Reset Configuration Values"),

    _RDUMP (CCSR_PORPLLSR, REG_SIZE_32),
    _RDUMP (CCSR_PORBMSR, REG_SIZE_32),
    _RDUMP (CCSR_PORIMPSCR, REG_SIZE_32),
    _RDUMP (CCSR_PORDEVSR, REG_SIZE_32),
    _RDUMP (CCSR_PORDBGMSR, REG_SIZE_32),
    _RDUMP (CCSR_GPPORCR, REG_SIZE_32),

    _RINFO ("Global Utilities: Signal Multiplexing and GPIO Controls"),

    _RDUMP (CCSR_GPIOCR, REG_SIZE_32),
    _RDUMP (CCSR_GPOUTDR, REG_SIZE_32),
    _RDUMP (CCSR_GPINDR, REG_SIZE_32),
    _RDUMP (CCSR_PMUXCR, REG_SIZE_32),

    _RINFO ("Global Utilities: Device Disables"),    

    _RDUMP (CCSR_DEVDISR, REG_SIZE_32),

    _RINFO ("Global Utilities: Power Management Register"),

    _RDUMP (CCSR_POWMGTCSR, REG_SIZE_32),

    _RINFO ("Global Utilities: Interrupt Reporting"),

    _RDUMP (CCSR_MCPSUMR, REG_SIZE_32),

    _RINFO ("Global Utilities: Version Registers"),

    _RDUMP (CCSR_PVR, REG_SIZE_32),
    _RDUMP (CCSR_SVR, REG_SIZE_32),

    _RINFO ("Debug Control"),

    _RDUMP (CCSR_CLKOCR, REG_SIZE_32),
    _RDUMP (CCSR_DDRDLLCR, REG_SIZE_32),
    _RDUMP (CCSR_LBDLLCR, REG_SIZE_32),

    _RSTOP,

    _RINFO ("Performance Monitor Control Registers"),

    _RDUMP (CCSR_PMGC0, REG_SIZE_32),
    _RDUMP (CCSR_PMLCA0, REG_SIZE_32),
    _RDUMP (CCSR_PMLCB0, REG_SIZE_32),
    _RDUMP (CCSR_PMC0U, REG_SIZE_32),
    _RDUMP (CCSR_PMC0L, REG_SIZE_32),
    _RDUMP (CCSR_PMLCA1, REG_SIZE_32),
    _RDUMP (CCSR_PMLCB1, REG_SIZE_32),
    _RDUMP (CCSR_PMC1, REG_SIZE_32),
    _RDUMP (CCSR_PMLCA2, REG_SIZE_32),
    _RDUMP (CCSR_PMLCB2, REG_SIZE_32),
    _RDUMP (CCSR_PMC2, REG_SIZE_32),
    _RDUMP (CCSR_PMLCA3, REG_SIZE_32),
    _RDUMP (CCSR_PMLCB3, REG_SIZE_32),
    _RDUMP (CCSR_PMC3, REG_SIZE_32),
    _RDUMP (CCSR_PMLCA4, REG_SIZE_32),
    _RDUMP (CCSR_PMLCB4, REG_SIZE_32),
    _RDUMP (CCSR_PMC4, REG_SIZE_32),
    _RDUMP (CCSR_PMLCA5, REG_SIZE_32),
    _RDUMP (CCSR_PMLCB5, REG_SIZE_32),
    _RDUMP (CCSR_PMC5, REG_SIZE_32),
    _RDUMP (CCSR_PMLCA6, REG_SIZE_32),
    _RDUMP (CCSR_PMLCB6, REG_SIZE_32),
    _RDUMP (CCSR_PMC6, REG_SIZE_32),
    _RDUMP (CCSR_PMLCA7, REG_SIZE_32),
    _RDUMP (CCSR_PMLCB7, REG_SIZE_32),
    _RDUMP (CCSR_PMC7, REG_SIZE_32),
    _RDUMP (CCSR_PMLCA8, REG_SIZE_32),
    _RDUMP (CCSR_PMLCB8, REG_SIZE_32),
    _RDUMP (CCSR_PMC8, REG_SIZE_32),

    _RSTOP,

    _RINFO ("Debug and Watchpoint Monitor Registers"),

    _RDUMP (CCSR_WMCR0, REG_SIZE_32),
    _RDUMP (CCSR_WMCR1, REG_SIZE_32),
    _RDUMP (CCSR_WMAR, REG_SIZE_32),
    _RDUMP (CCSR_WMAMR, REG_SIZE_32),
    _RDUMP (CCSR_WMTMR, REG_SIZE_32),
    _RDUMP (CCSR_WMSR, REG_SIZE_32),

    _RINFO ("Trace Buffer Registers"),

    _RDUMP (CCSR_TBCR0, REG_SIZE_32),
    _RDUMP (CCSR_TBCR1, REG_SIZE_32),
    _RDUMP (CCSR_TBAR, REG_SIZE_32),
    _RDUMP (CCSR_TBAMR, REG_SIZE_32),
    _RDUMP (CCSR_TBTMR, REG_SIZE_32),
    _RDUMP (CCSR_TBSR, REG_SIZE_32),
    _RDUMP (CCSR_TBACR, REG_SIZE_32),
    _RDUMP (CCSR_TBADHR, REG_SIZE_32),
    _RDUMP (CCSR_TBADR, REG_SIZE_32),

    _RINFO ("Context ID Registers"),

    _RDUMP (CCSR_PCIDR, REG_SIZE_32),
    _RDUMP (CCSR_CCIDR, REG_SIZE_32),

    _RINFO ("Other Registers"),

    _RDUMP (CCSR_TOSR, REG_SIZE_32),

    _RSTOP,

    _REND 

    };

/* forward declarations */

LOCAL void dumpIt (UINT32 regOffset);
void mpc8540CcsDump (void);
void mpc8540LawDump (void);
void mpc8540EcmDump (void);
void mpc8540DdrCtlDump (void);
void mpc8540I2cDump (void);
void mpc8540DuartDump (void);
void mpc8540LbcDump (void);
void mpc8540PciAccDump (void);
void mpc8540PciATMUDump (void);
void mpc8540PciErrDump (void);
void mpc8540L2SramDump (void);
void mpc8540DmaDump (void);
void mpc8540Tsec1Dump (void);
void mpc8540Tsec2Dump (void);
void mpc8540FecDump (void);
void mpc8540PicGlblDump (void);
void mpc8540PicIntlDump (void);
void mpc8540PicPerCPUDump (void);
void mpc8540RapidIoDump (void);
void mpc8540GlblUtilDump (void);
void mpc8540PerfMonDump (void);
void mpc8540DbugWpDump (void);
void mpc8540MemRegDump (void);
void coreLbcShow (void);
void coreShow (void);
LOCAL void tlbShow1 (MAS mas);
void tlbShow (UINT32 tlbSel);
void tlbAllShow (void);
LOCAL void lawShow (UINT32 setNo, UINT32 lawbar, UINT32 lawar);
void lawAllShow (void);
LOCAL void pciAtmuOutShow1 (UINT32 set, PARO paro); 
LOCAL void pciAtmuInShow1 (UINT32 set, PARI pari);
void pciAtmuOutShow (void);
void pciAtmuInShow (void);
void pciAtmuAllShow (void);
void mpc8540Show (void);
void mpc8540DdrCtlShow (void);

/* externals */

IMPORT void tlbEntryRead (MAS * mas, UINT32 mas0, UINT32 mas2);
IMPORT UINT32 sysCpuBusSpd (void);
IMPORT UINT32 sysCoreFreqGet (void);
IMPORT UINT32 sysPciBusASpdGet (void);

/******************************************************************************
*
* dumpIt - "Dump" information from one segment of the mpc8540RegDumpTbl
*
* This function is given a register offset from which to begin dumping
* from table mpc8540RegDumpTbl.  It searches for this beginning point in the
* table and once it is found, begins dumping from that point (minus one to 
* catch the _RINFO description) and continues in the table until it 
* encounters an _RSTOP.
*
* RETURNS: NA
*/

LOCAL void dumpIt
    (
    UINT32 regOffset
    )
    {
    int i;

    i = 0;

    /* Find location in table at which to start */

    while (mpc8540RegDumpTbl[i].regOff != REND)
	{
	if (mpc8540RegDumpTbl[i].regOff == regOffset)
	    break;
	i++;
	}

    if (mpc8540RegDumpTbl[i].regOff != REND)
	{

	/* Point to the _RINFO stuff that comes prior to our starting point */

	i--;

	/* Dump until we hit an _RSTOP */

	while (mpc8540RegDumpTbl[i].regOff != RSTOP)
	    {
	    if (mpc8540RegDumpTbl[i].regOff == RINFO)

		/* It's an "info" (Description commenary) line */

		printf("\n\r%s\n\r\n\r",mpc8540RegDumpTbl[i].label);
            else
		{
	
		/* It's an actual register line to display */

	        printf("%-36s",mpc8540RegDumpTbl[i].label);
		if (mpc8540RegDumpTbl[i].regSize == REG_SIZE_32)
		    {
	            printf(" @0x%08x = 0x%08x\n\r",
		           CCSBAR+mpc8540RegDumpTbl[i].regOff,
		           CCSR_READ32 (CCSBAR, mpc8540RegDumpTbl[i].regOff));
		    }
		else if (mpc8540RegDumpTbl[i].regSize == REG_SIZE_8)
		    {
	            printf(" @0x%08x = 0x%02x\n\r",
		           CCSBAR+mpc8540RegDumpTbl[i].regOff,
		           CCSR_READ08 (CCSBAR, mpc8540RegDumpTbl[i].regOff));
		    }
		}
	    i++;
	    }
	}
    }

/******************************************************************************
* 
* mpc8540CcsDump - Dump "Ccs" segment of mpc8540RegDumpTbl
*
* RETURNS: NA
*/

void mpc8540CcsDump (void)
    {
    printf("\n\r\n\rmpc8540CcsDump():\n\r");
    dumpIt(CCSR_CCSRBAR);
    }

/******************************************************************************
* 
* mpc8540LawDump - Dump "Law" segment of mpc8540RegDumpTbl
*
* RETURNS: NA
*/

void mpc8540LawDump (void)
    {
    printf("\n\r\n\rmpc8540LawDump():\n\r");
    dumpIt(CCSR_LAWBAR0);
    }

/******************************************************************************
* 
* mpc8540EcmDump - Dump "Law" segment of mpc8540RegDumpTbl
*
* RETURNS: NA
*/

void mpc8540EcmDump (void)
    {
    printf("\n\r\n\rmpc8540EcmDump():\n\r");
    dumpIt(CCSR_EEBACR);
    }

/******************************************************************************
* 
* mpc8540DdrCtlDump - Dump "DdrCtl" segment of mpc8540RegDumpTbl
*
* RETURNS: NA
*/

void mpc8540DdrCtlDump (void)
    {
    printf("\n\r\n\rmpc8540DdrCtlDump():\n\r");
    dumpIt(CCSR_CS0_BNDS);
    }

/******************************************************************************
* 
* mpc8540I2cDump - Dump "Iwc" segment of mpc8540RegDumpTbl
*
* RETURNS: NA
*/

void mpc8540I2cDump (void)
    {
    printf("\n\r\n\rmpc8540I2cDump():\n\r");
    dumpIt(CCSR_I2CADR);
    }

/******************************************************************************
* 
* mpc8540DuartDump - Dump "Duart" segment of mpc8540RegDumpTbl
*
* RETURNS: NA
*/

void mpc8540DuartDump (void)
    {
    printf("\n\r\n\rmpc8540DuartDump():\n\r");
    dumpIt(CCSR_URBR0);
    }

/******************************************************************************
* 
* mpc8540LbcDump - Dump "Lbc" segment of mpc8540RegDumpTbl
*
* RETURNS: NA
*/

void mpc8540LbcDump (void)
    {
    printf("\n\r\n\rmpc8540LbcDump():\n\r");
    dumpIt(CCSR_BR0);
    }

/******************************************************************************
* 
* mpc8540PciAccDump - Dump "PciAcc" segment of mpc8540RegDumpTbl
*
* RETURNS: NA
*/

void mpc8540PciAccDump (void)
    {
    printf("\n\r\n\rmpc8540PciAccDump():\n\r");
    dumpIt(CCSR_CFG_ADDR);
    }

/******************************************************************************
* 
* mpc8540PciATMUDump - Dump "PciATMU" segment of mpc8540RegDumpTbl
*
* RETURNS: NA
*/

void mpc8540PciATMUDump (void)
    {
    printf("\n\r\n\rmpc8540PciATMUDump():\n\r");
    dumpIt(CCSR_POTAR0);
    }

/******************************************************************************
* 
* mpc8540PciErrDump - Dump "PciErr" segment of mpc8540RegDumpTbl
*
* RETURNS: NA
*/

void mpc8540PciErrDump (void)
    {
    printf("\n\r\n\rmpc8540PciErrDump():\n\r");
    dumpIt(CCSR_ERR_DR);
    }

/******************************************************************************
* 
* mpc8540L2SramDump - Dump "L2Sram" segment of mpc8540RegDumpTbl
*
* RETURNS: NA
*/

void mpc8540L2SramDump (void)
    {
    printf("\n\r\n\rmpc8540L2SramDump():\n\r");
    dumpIt(CCSR_L2CTL);
    }

/******************************************************************************
* 
* mpc8540DmaDump - Dump "Dma" segment of mpc8540RegDumpTbl
*
* RETURNS: NA
*/

void mpc8540DmaDump (void)
    {
    printf("\n\r\n\rmpc8540DmaDump():\n\r");
    dumpIt(CCSR_MR0);
    }

/******************************************************************************
* 
*  mpc8540Tsec1Dump - Dump "Tsec1" segment of mpc8540RegDumpTbl
*
* RETURNS: NA
*/

void mpc8540Tsec1Dump (void)
    {
    printf("\n\r\n\rmpc8540Tsec1Dump():\n\r");
    dumpIt(CCSR_TSEC1_IEVENT);
    }

/******************************************************************************
* 
* mpc8540Tsec2Dump - Dump "Tsec2" segment of mpc8540RegDumpTbl
*
* RETURNS: NA
*/

void mpc8540Tsec2Dump (void)
    {
    printf("\n\r\n\rmpc8540Tsec2Dump():\n\r");
    dumpIt(CCSR_TSEC2_IEVENT);
    }

/******************************************************************************
* 
* mpc8540FecDump - Dump "Fec" segment of mpc8540RegDumpTbl
*
* RETURNS: NA
*/

void mpc8540FecDump (void)
    {
    printf("\n\r\n\rmpc8540FecDump():\n\r");
    dumpIt(CCSR_FEC_IEVENT);
    }

/******************************************************************************
* 
* mpc8540PicGlblDump - Dump "PicGlbl" segment of mpc8540RegDumpTbl
*
* RETURNS: NA
*/

void mpc8540PicGlblDump (void)
    {
    printf("\n\r\n\rmpc8540PicGlblDump():\n\r");
    dumpIt(CCSR_GLBL_IPIDR0);
    }

/******************************************************************************
* 
* mpc8540PicIntlDump - Dump "PicIntl" segment of mpc8540RegDumpTbl
*
* RETURNS: NA
*/

void mpc8540PicIntlDump (void)
    {
    printf("\n\r\n\rmpc8540PicIntlDump():\n\r");
    dumpIt(CCSR_EIVPR0);
    }

/******************************************************************************
* 
* mpc8540PicPerCPUDump - Dump "PicPerCPU" segment of mpc8540RegDumpTbl
*
* RETURNS: NA
*/

void mpc8540PicPerCPUDump (void)
    {
    printf("\n\r\n\rmpc8540PicPerCPUDump():\n\r");
    dumpIt(CCSR_CPU_IPIDR0);
    }

/******************************************************************************
* 
* mpc8540RapidIoDump - Dump "RapidIo" segment of mpc8540RegDumpTbl
*
* RETURNS: NA
*/

void mpc8540RapidIoDump (void)
    {
    printf("\n\r\n\rmpc8540RapidIoDump():\n\r");
    dumpIt(CCSR_RIO_DIDCAR);
    }

/******************************************************************************
* 
* mpc8540GlblUtilDump - Dump "GlblUtil" segment of mpc8540RegDumpTbl
*
* RETURNS: NA
*/

void mpc8540GlblUtilDump (void)
    {
    printf("\n\r\n\rmpc8540GlblUtilDump():\n\r");
    dumpIt(CCSR_PORPLLSR);
    }

/******************************************************************************
* 
* mpc8540PerfMonDump - Dump "PerfMon" segment of mpc8540RegDumpTbl
*
* RETURNS: NA
*/

void mpc8540PerfMonDump (void)
    {
    printf("\n\r\n\rmpc8540PerfMonDump():\n\r");
    dumpIt(CCSR_PMGC0);
    }

/******************************************************************************
* 
* mpc8540DbugWpDump - Dump "DbugWp" segment of mpc8540RegDumpTbl
*
* RETURNS: NA
*/

void mpc8540DbugWpDump (void)
    {
    printf("\n\r\n\rmpc8540DbugWpDump():\n\r");
    dumpIt(CCSR_WMCR0);
    }

/*****************************************************************************
*
* mpc8540MemRegDump - Dump in raw format all of the mpc8540 mem mapped registers
*
* RETURNS: NA
*/

void mpc8540MemRegDump (void)
    {
    printf("\n\r\n\rmpc8540MemRegDump():\n");
    mpc8540CcsDump ();
    mpc8540LawDump ();
    mpc8540EcmDump ();
    mpc8540DdrCtlDump ();
    mpc8540I2cDump ();
    mpc8540DuartDump ();
    mpc8540LbcDump ();
    mpc8540PciAccDump ();
    mpc8540PciATMUDump ();
    mpc8540PciErrDump ();
    mpc8540L2SramDump ();
    mpc8540DmaDump ();
    mpc8540Tsec1Dump ();
    mpc8540Tsec2Dump ();
    mpc8540FecDump ();
    mpc8540PicGlblDump ();
    mpc8540PicIntlDump ();
    mpc8540PicPerCPUDump ();
    mpc8540RapidIoDump ();
    mpc8540GlblUtilDump ();
    mpc8540PerfMonDump ();
    mpc8540DbugWpDump ();
    }

/***************************************************************************
*
* coreLbcShow - Show routine for local bus controller
* 
* RETURNS - NONE
*/

void coreLbcShow (void)
    {
    UINT32 tmp, tmp2;

    tmp = CCSR_READ32 (CCSBAR, CCSR_BR0);
    tmp2 =  CCSR_READ32 (CCSBAR, CCSR_OR0);
    printf("Local bus BR0 = 0x%x\tOR0 = 0x%x\n", tmp, tmp2);

    tmp = CCSR_READ32 (CCSBAR, CCSR_BR1);
    tmp2 =  CCSR_READ32 (CCSBAR, CCSR_OR1);
    printf("Local bus BR1 = 0x%x\tOR1 = 0x%x\n", tmp, tmp2);

    tmp = CCSR_READ32 (CCSBAR, CCSR_BR2);
    tmp2 =  CCSR_READ32 (CCSBAR, CCSR_OR2);
    printf("Local bus BR2 = 0x%x\tOR2 = 0x%x\n", tmp, tmp2);

    tmp = CCSR_READ32 (CCSBAR, CCSR_BR3);
    tmp2 =  CCSR_READ32 (CCSBAR, CCSR_OR3);
    printf("Local bus BR3 = 0x%x\tOR3 = 0x%x\n", tmp, tmp2);

    tmp = CCSR_READ32 (CCSBAR, CCSR_BR4);
    tmp2 =  CCSR_READ32 (CCSBAR, CCSR_OR4);
    printf("Local bus BR4 = 0x%x\tOR4 = 0x%x\n", tmp, tmp2);

    tmp = CCSR_READ32 (CCSBAR, CCSR_BR5);
    tmp2 =  CCSR_READ32 (CCSBAR, CCSR_OR5);
    printf("Local bus BR5 = 0x%x\tOR5 = 0x%x\n", tmp, tmp2);

    tmp = CCSR_READ32 (CCSBAR, CCSR_BR6);
    tmp2 =  CCSR_READ32 (CCSBAR, CCSR_OR6);
    printf("Local bus BR6 = 0x%x\tOR6 = 0x%x\n", tmp, tmp2);

    tmp = CCSR_READ32 (CCSBAR, CCSR_BR7);
    tmp2 =  CCSR_READ32 (CCSBAR, CCSR_OR7);
    printf("Local bus BR7 = 0x%x\tOR7 = 0x%x\n", tmp, tmp2);

    tmp = CCSR_READ32 (CCSBAR, CCSR_LBCR);
    printf("Local bus LBCR = 0x%x\n", tmp);

    tmp = CCSR_READ32 (CCSBAR, CCSR_LCRR);
    printf("Local bus LCRR = 0x%x\n", tmp);
    }

/***************************************************************************
*
* coreShow - Show routine for core registers
* 
* RETURNS - NONE
*/

void coreShow (void)
    {
    UINT32 tmp, tmp2;

    tmp = vxMsrGet();
    printf("MSR - 0x%x\n", tmp);
    printf("      UCLE-%x SPE-%x WE-%x CE-%x EE-%x PR-%x ME-%x\n",
           xbit32(tmp,37), xbit32(tmp,38), xbit32(tmp,45), xbit32(tmp,46),
           xbit32(tmp,48), xbit32(tmp,49), xbit32(tmp,51));
    printf("      UBLE-%x DE-%x IS-%x DS-%x PMM-%x\n",
           xbit32(tmp,53), xbit32(tmp,54), xbit32(tmp,58), xbit32(tmp,59),
           xbit32(tmp,61));
    tmp = vxHid0Get();
    tmp2 = vxHid1Get();
    printf("HID0 = 0x%x, HID1 = 0x%x\n", tmp, tmp2);
    tmp = vxL1CSR0Get();
    printf("L1CSR0: cache is %s - 0x%x\n", tmp&1?"ON":"OFF", tmp);
    tmp = vxL1CSR1Get();
    printf("L1CSR1: Icache is %s - 0x%x\n", tmp&1?"ON":"OFF", tmp);
    tmp = vxL1CFG0Get();
    tmp2 = vxL1CFG1Get();
    printf("L1CFG0 = 0x%x, L1CFG1 = 0x%x\n", tmp, tmp2);
    tmp = CCSR_READ32 (CCSBAR, CCSR_L2CTL);
    printf("L2CTL - 0x%x\n", tmp);
    printf("        l2 is %s\n", tmp&0x80000000?"ON":"OFF");
    printf("        l2siz-%x l2blksz-%x l2do-%x l2io-%x\n",
           (xbit0(tmp,2)<<1)|xbit0(tmp,3), (xbit0(tmp,4)<<1)|xbit0(tmp,5),
           xbit0(tmp,9), xbit0(tmp,10));
    printf("        l2pmextdis-%x l2intdis-%x l2sram-%x\n",
           xbit0(tmp,11), xbit0(tmp,12),
           (xbit0(tmp,13)<<2)|(xbit0(tmp,14)<<1)|xbit0(tmp,15));
    tmp = CCSR_READ32 (CCSBAR, CCSR_L2SRBAR0);
    tmp2 = CCSR_READ32 (CCSBAR, CCSR_L2SRBAR1);
    printf("L2SRBAR0 - 0x%x\n", tmp);
    printf("L2SRBAR1 - 0x%x\n", tmp2);

    printf("Core Freq = %3d Hz\n", sysCoreFreqGet ());
    printf("CCB Freq = %3d Hz\n", sysCpuBusSpd ());
    printf("PCI A Freq = %3d Hz\n", sysPciBusASpdGet ());
    printf("CPM Freq = %3d Hz\n", sysCpuBusSpd ());

    }

/******************************************************************************
*
* tlbShow1 - Display information on 1 TLB entry.
*
* This function will take a TLB 4 register structure and print a formatted
* display of the information contained therein.
*
* RETURNS: NA
*/

LOCAL void tlbShow1 
    (
    MAS    mas		/* 4-register TLB entry */
    )
    {
    UINT32 tlbSel; 	/* TLB selector (0 or 1) */
    UINT32 in1; 
    UINT32 in2; 
    UINT32 out1; 
    UINT32 out2;
    UINT32 i;
    UINT32 size;
    
    tlbSel = PPC_MAS0_TLBSEL_VAL(mas.mas0);
    printf("\n");
    printf("mas0 = 0x%08x, mas1 = 0x%08x, mas2 = 0x%08x, mas3 = 0x%08x\n",
    mas.mas0, mas.mas1, mas.mas2, mas.mas3);
    
    printf("  TLBSEL = %1x,", PPC_MAS0_TLBSEL_VAL(mas.mas0));
    printf("  ESEL   = %02x,\n", PPC_MAS0_ESEL_VAL(mas.mas0));
    printf("  V      = %1x,", PPC_MAS1_V_VAL(mas.mas1));

    if (tlbSel != 0)
        printf("  IPROT  = %1x,", PPC_MAS1_IPROT_VAL(mas.mas1));

    printf("  TID    = %02x,", PPC_MAS1_TID_VAL(mas.mas1));
    printf("  TS     = %1x", PPC_MAS1_TS_VAL(mas.mas1));
    printf("  TSIZE  = %1x\n", PPC_MAS1_TSIZE_VAL(mas.mas1));
    
    printf("  EPN    = %05x", PPC_MAS2_EPN_VAL(mas.mas2));
    printf("  WIMGE  = %d%d%d%d%d\n", PPC_MAS2_W_VAL(mas.mas2), 
                                      PPC_MAS2_I_VAL(mas.mas2), 
                                      PPC_MAS2_M_VAL(mas.mas2), 
                                      PPC_MAS2_G_VAL(mas.mas2), 
                                      PPC_MAS2_E_VAL(mas.mas2));
    
    printf("  RPN    = %05x", PPC_MAS3_RPN_VAL(mas.mas3));
    printf("  UX.SX.UW.SW.UR.SR = %d%d%d%d%d%d\n", PPC_MAS3_UX_VAL(mas.mas3),
						   PPC_MAS3_SX_VAL(mas.mas3),
						   PPC_MAS3_UW_VAL(mas.mas3),
						   PPC_MAS3_SW_VAL(mas.mas3),
						   PPC_MAS3_UR_VAL(mas.mas3),
						   PPC_MAS3_SR_VAL(mas.mas3));
  				                    
    
    /* Compute mapping range */

    in1 = mas.mas2 & PPC_MAS2_EPN_MASK;
    i = PPC_MAS1_TSIZE_VAL(mas.mas1);
    i <<= 1;
    size = 0x400;
    
    while (i > 0)	/* Convert TSIZE to real address range */
        {
        size <<= 1;
        i--;
        }
    
    in2 = in1 + size - 1;
    
    out1 = mas.mas3 & PPC_MAS3_RPN_MASK;
    out2 = out1 + size - 1;
    
    printf ("    Maps: 0x%08x thru 0x%08x -- to -- 0x%08x thru 0x%08x\n",
    	in1, in2, out1, out2);
    }

/******************************************************************************
*
* tlbShow - Display all the information from one TLB.
*
* This function displays all of the information in either TLB1 or TLB0
* depending on the selection paramater passed in to it.
*
* RETURNS: NA
*/

void tlbShow
    (
    UINT32 tlbSel	/* TLB array number (0 or 1) */
    )
    {
    MAS mas;
    UINT32 mas0;
    UINT32 mas2;
    UINT32 epn;
    UINT32 esel;

    if (tlbSel == 1)
	{
	printf ("\n\nValid TLB1 entries:\n");
	printf (    "-------------------\n\n");
        epn = 0;	/* Ignored for TLB1 but we'll set it anyway */

        for (esel = 0; esel <= 15; esel++)
            {
            mas0 = (tlbSel << PPC_MAS0_TLBSEL_BIT) | 
		   (esel << PPC_MAS0_ESEL_BIT);

            mas2 = (epn << PPC_MAS2_EPN_BIT);
            tlbEntryRead (&mas, mas0, mas2);

            if ((mas.mas1 & PPC_MAS1_V_MASK) != 0) /* If entry valid ... */
	        tlbShow1 (mas);
            }
	}

    else if (tlbSel == 0)
	{
	printf ("\n\nValid TLB0 entries:\n");
	printf (    "-------------------\n\n");

        for (epn = 0; epn <= 0xfffff; epn++)
            {
            esel = 0;
            mas0 = (tlbSel << PPC_MAS0_TLBSEL_BIT) | 
		   (esel << PPC_MAS0_ESEL_BIT);

            mas2 = (epn << PPC_MAS2_EPN_BIT);
            tlbEntryRead (&mas, mas0, mas2);

            if ((mas.mas1 & PPC_MAS1_V_MASK) != 0) /* If entry valid ... */
	        {
	        if (PPC_MAS2_EPN_VAL(mas.mas2) == epn)
	            tlbShow1 (mas);
	        }

            esel = 1;		/* Now look in alternate "way" */
            mas0 = (tlbSel << PPC_MAS0_TLBSEL_BIT) | 
		   (esel << PPC_MAS0_ESEL_BIT);

            mas2 = (epn << PPC_MAS2_EPN_BIT);
            tlbEntryRead (&mas,mas0,mas2);
            if ((mas.mas1 & PPC_MAS1_V_MASK) != 0)
	        {
	        if (PPC_MAS2_EPN_VAL(mas.mas2) == epn)
	            tlbShow1 (mas);
                }
            }
	}
    }

/******************************************************************************
*
* tlbAllShow - Display all of the active TLB entries
*
* This function displays all of the information in the TLB entries,
* first displaying TLB1 and then TLB0.
*
* RETURNS: NA
*/ 

void tlbAllShow (void)
    {
    tlbShow(1);
    tlbShow(0);
    }

/******************************************************************************
*
* lawShow - Display the information from one local access register set
*
* This function displays the information from one particular access
* register set.
*
* RETURN: NA
*
*/

LOCAL void lawShow
    (
    UINT32 setNo,
    UINT32 lawbar,
    UINT32 lawar 
    )
    {
    UINT32 baseAddr;
    UINT32 byteCount;
    UINT32 topAddr;

    printf ("\nLAWBAR%d =  0x%08x  LAWAR%d =  0x%08x - ", 
	    setNo, lawbar, setNo, lawar);
    if ((lawar & CCSR_LAWAR_EN_MASK) == 0)
	printf("DISABLED\n");
    else
	{
	baseAddr = CCSR_LAWBAR_BASE_ADDR_DECODE(lawbar);
	byteCount = 1 << (((lawar & CCSR_LAWAR_SZ_MASK) >> CCSR_LAWAR_SZ_BIT) 
			    + 1);
	topAddr = baseAddr + byteCount;
	printf("\n  Maps 0x%08x thru 0x%08x (0x%x bytes)\n",
		baseAddr, topAddr-1, byteCount); 
        printf("    Target interface = ");
	switch ((lawar & CCSR_LAWAR_TRGT_IF_MASK) >> CCSR_LAWAR_TRGT_IF_BIT)
	    {
	    case 0x0:
		printf ("PCI/PCI-X\n");
		break;
	    case 0x4:
		printf ("Local Bus\n");
		break;
	    case 0xc:
		printf ("RapidIO\n");
		break;
	    case 0xf:
		printf ("DDR SDRAM\n");
		break;
	    default:
		printf ("Unknown\n");
		break;
	    }
	}
    }

/******************************************************************************
*
* lawAllShow - Display the active local access windows
*
* This function displays the information in each of the 8 sets of 
* local access windows (LAWBARn/LAWARn)
*
* RETURN: NA
*
*/

void lawAllShow (void)
    {
    UINT32 lawbar;
    UINT32 lawar;
    UINT32 setNo = 0;
    UINT32 gap = CCSR_LAWBAR1 - CCSR_LAWBAR0;

    printf("Local Access Window Settings:\n");
    printf("-----------------------------\n\n");

    for (setNo = 0; setNo <= 7; setNo++)
	{
	lawbar = CCSR_READ32 (CCSBAR, CCSR_LAWBAR0 + (setNo * gap)); 
	lawar  = CCSR_READ32 (CCSBAR, CCSR_LAWAR0 + (setNo * gap));
	lawShow (setNo, lawbar, lawar);
	}
    }

/******************************************************************************
*
* pciAtmuOutShow1 - Show one outbound PCI access register set
*
* This function displays one outbound PCI access register set with formatted
* breakdown of the information contained therein.
*
* RETURNS: NA
*/

LOCAL void pciAtmuOutShow1
    (
    UINT32 set,
    PARO paro 
    )
    {
    UINT32 size;
    UINT32 rtt;
    UINT32 wtt;

    printf ("POTAR%d(0x%08x), POTEAR%d(0x%08x), "
	    "POWBAR%d(0x%08x), POWAR%d(0x%08x)\n", set, paro.potar,
	    set, paro.potear, set, paro.powbar, set, paro.powar);

    if (CCSR_POWAR_EN_VAL(paro.powar) == 0)
	{
	printf("  DISABLED\n\n");
	return;
	}

    size = MPC8540_PCI_SIZE_DECODE(CCSR_POWAR_OWS_VAL(paro.powar));
    rtt = CCSR_POWAR_RTT_VAL(paro.powar);
    wtt = CCSR_POWAR_WTT_VAL(paro.powar);

    printf("  Maps local 0x%08x thru 0x%08x  -- to -- PCI 0x%08x thru 0x%08x\n",
	   CCSR_PAR_ADDR_DECODE(paro.powbar), 
	   CCSR_PAR_ADDR_DECODE(paro.powbar) + size - 1,
	   CCSR_PAR_ADDR_DECODE(paro.potar), 
	   CCSR_PAR_ADDR_DECODE(paro.potar) + size - 1);
    printf ("    Read transaction type: %s, Write transaction type: %s\n\n",
	    (rtt == 0x4)?"Memory Read":(rtt == 0x8)?"I/O Write":"Reserved",
	    (wtt == 0x4)?"Memory Write":(wtt == 0x8)?"I/O Write":"Reserved");
    }

/******************************************************************************
*
* pciAtmuInShow1 - Show one inbound PCI access register set
*
* This function displays one inbound PCI access register set with formatted
* breakdown of the information contained therein.
*
* RETURNS: NA
*/

LOCAL void pciAtmuInShow1
    (
    UINT32 set,
    PARI pari 
    )
    {
    UINT32 size;
    UINT32 rtt;
    UINT32 wtt;
    UINT32 tgi;
    UINT32 pf;

    if (set != 1)
        printf ("PITAR%d(%08x), PIWBAR%d(%08x), "
	        "PIWBEAR%d(%08x), PIWAR%d(%08x)\n", set, pari.pitar,
	        set, pari.piwbar, set, pari.piwbear, set, pari.piwar);
    else
        printf ("PITAR%d(%08x), PIWBAR%d(%08x), "
	        ".................., PIWAR%d(%08x)\n", set, pari.pitar,
	        set, pari.piwbar, set, pari.piwar);

    if (CCSR_PIWAR_EN_VAL(pari.piwar) == 0)
	{
	printf("  DISABLED\n\n");
	return;
	}

    size = MPC8540_PCI_SIZE_DECODE(CCSR_PIWAR_IWS_VAL(pari.piwar));
    rtt = CCSR_PIWAR_RTT_VAL(pari.piwar);
    wtt = CCSR_PIWAR_WTT_VAL(pari.piwar);
    tgi = CCSR_PIWAR_TGI_VAL(pari.piwar);
    pf  = CCSR_PIWAR_PF_VAL (pari.piwar);

    printf("  Maps PCI 0x%08x thru 0x%08x  -- to -- Local 0x%08x thru 0x%08x\n",
	   CCSR_PAR_ADDR_DECODE(pari.piwbar), 
	   CCSR_PAR_ADDR_DECODE(pari.piwbar) + size - 1,
	   CCSR_PAR_ADDR_DECODE(pari.pitar), 
	   CCSR_PAR_ADDR_DECODE(pari.pitar) + size - 1);

    printf ("    %s, ",(pf == 1)?"Prefetchable":"NonPrefetchable");
    printf ("    Target Interface: %s\n",
	    (tgi == 0xc)?"RapidIO":(tgi == 0xf)?"Local Memory":"Reserved");

    if (tgi == 0xc) /* If RapidIO */
	{
        printf ("    Read transaction type: %s\n",
	        (rtt == 0x4)?"Read":"Reserved");
        printf ("    Write transaction type: %s\n",
	        (wtt == 0x4)?"Write":"Reserved");
	}
    if (tgi == 0xf)
	{
        printf ("    Read transaction type: %s\n",
		(rtt == 4)?"Read and don't snoop":
		    (rtt == 5)?"Read and snoop":
		    (rtt == 7)?"Read and unlock L2 cache line":"Reserved");

        printf ("    Write transaction type: %s\n\n",
		(rtt == 4)?"Write and don't snoop":
		    (rtt == 5)?"Write and snoop":
		    (rtt == 6)?"Write and allocate L2 cache line":
		    (rtt == 7)?"Write, allocate and lock L2 cache line":
		    "Reserved");
	}
    }

/******************************************************************************
*
* pciAtmuOutShow - Show all outbound PCI access registers 
*
* This function displays all of the outbound PCI access registers 
* complete with formatted breakdown of the information contained therein.
*
* RETURNS: NA
*/

void pciAtmuOutShow (void)
    {
    PARO paro;
    int i;
    UINT32 gap = CCSR_POTAR1 - CCSR_POTAR0;

    printf("PCI/X Outbound Access Registers\n");
    printf("-------------------------------\n\n");

    for (i=0; i<=4; i++)
	{
	paro.potar =  CCSR_READ32 (CCSBAR, CCSR_POTAR0  + (gap * i));
	paro.potear = CCSR_READ32 (CCSBAR, CCSR_POTEAR0 + (gap * i));
	paro.powbar = CCSR_READ32 (CCSBAR, CCSR_POWBAR0 + (gap * i));
	paro.powar =  CCSR_READ32 (CCSBAR, CCSR_POWAR0  + (gap * i));

	pciAtmuOutShow1 (i, paro);
	}
    }

/******************************************************************************
*
* pciAtmuInShow - Show all inbound PCI access registers with formatted 
* description.
*
* This function displays all of the inbound PCI access registers 
* complete with formatted breakdown of the information contained therein.
*
* RETURNS: NA
*/

void pciAtmuInShow (void)
    {
    PARI pari;
    int i;
    UINT32 gap = CCSR_PITAR2 - CCSR_PITAR3;

    printf("PCI/X Inbound Access Registers\n");
    printf("------------------------------\n\n");

    for (i=3; i>=1; i--)
	{
	pari.pitar =   CCSR_READ32 (CCSBAR, CCSR_PITAR3 + (gap * (3-i)));
	pari.piwbar =  CCSR_READ32 (CCSBAR, CCSR_PIWBAR3 + (gap * (3-i)));
	if (i != 1)
	    pari.piwbear = CCSR_READ32 (CCSBAR, CCSR_PIWBEAR3 + (gap * (3-i)));
	pari.piwar =   CCSR_READ32 (CCSBAR, CCSR_PIWAR3 + (gap * (3-i)));

	pciAtmuInShow1 (i, pari);
	}
    }

/******************************************************************************
*
* pciAtmuAllShow - Show all PCI access registers with formatted description
*
* RETURNS: NA
*/

void pciAtmuAllShow (void)
    {
    printf("\n");
    pciAtmuOutShow ();
    pciAtmuInShow ();
    }

/******************************************************************************
*
* mpc8540DdrCtlShow - Show all DDR SDRAM memory controller registers with
* formatted description
*
* RETURNS: NA
*/

void mpc8540DdrCtlShow (void)
    {
    UINT32 reg1 = 0x0;
    UINT32 reg2 = 0x0;
    UINT32 startAddr = 0x0;
    UINT32 endAddr = 0x0;
    UINT32 temp = 0x0;

    printf("\n\r");

    /* Chip Select 0 */

    reg1 = CCSR_READ32(CCSBAR,CCSR_CS0_CONFIG);
    printf("CS0_CONFIG = 0x%08x\n\r", reg1);
    reg2 = CCSR_READ32(CCSBAR,CCSR_CS0_BNDS);
    printf("CS0_BNDS = 0x%08x\n\r", reg2);
    if (reg1 && DDR_SDRAM_CSn_CONFIG_CS_EN_MASK)
        {
        printf("  Chip Select 0 is enabled.\n\r");
        startAddr = ((reg2 & DDR_SDRAM_CSn_BNDS_SA_MASK) <<
                     DDR_SDRAM_CSn_BNDS_SA_SHIFT);
        endAddr = (((reg2 & DDR_SDRAM_CSn_BNDS_EA_MASK) <<
                    DDR_SDRAM_CSn_BNDS_EA_SHIFT)|0x00FFFFFF);
        printf("  0x%08x - 0x%08x\n\r", startAddr, endAddr);
        if (reg1 & DDR_SDRAM_CSn_CONFIG_AP_EN_MASK)
            printf("  AP_n_EN       = 0x1 - Auto Precharge enabled.\n\r");
        else
            printf("  AP_n_EN       = 0x0 - Auto Precharge disabled.\n\r");
        temp = ((reg1 & DDR_SDRAM_CSn_CONFIG_ROW_MASK) >>
                DDR_SDRAM_CSn_CONFIG_ROW_BIT);
        printf("  ROW_BITS_CS_n = 0x%x", temp);
        switch (temp)
            {
            case 0x0:
                printf(" - 12 row bits.\n\r");
                break;
            case 0x1:
                printf(" - 13 row bits.\n\r");
                break;
            case 0x2:
                printf(" - 14 row bits.\n\r");
                break;
            default:
                printf(" - reserved.\n\r");
                break;
            }
        temp = ((reg1 & DDR_SDRAM_CSn_CONFIG_COLUMN_MASK) >>
                DDR_SDRAM_CSn_CONFIG_COLUMN_BIT);
        printf("  COL_BITS_CS_n = 0x%x", temp);
        switch (temp)
            {
            case 0x0:
                printf(" - 8 column bits.\n\r");
                break;
            case 0x1:
                printf(" - 9 column bits.\n\r");
                break;
            case 0x2:
                printf(" - 10 column bits.\n\r");
                break;
            case 0x3:
                printf(" - 11 column bits.\n\r");
                break;
            default:
                printf(" - reserved.\n\r");
                break;
            }
        }
    else
        printf("  Chip Select 0 is disabled\n\r");

    /* Chip Select 1 */

    printf("\n");
    reg1 = CCSR_READ32(CCSBAR,CCSR_CS1_CONFIG);
    printf("CS1_CONFIG = 0x%08x\n\r", reg1);
    reg2 = CCSR_READ32(CCSBAR,CCSR_CS1_BNDS);
    printf("CS1_BNDS = 0x%08x\n\r", reg2);
    if (reg1 && DDR_SDRAM_CSn_CONFIG_CS_EN_MASK)
        {
        printf("Chip Select 1 is enabled.\n\r");
        startAddr = ((reg2 & DDR_SDRAM_CSn_BNDS_SA_MASK) <<
                     DDR_SDRAM_CSn_BNDS_SA_SHIFT);
        endAddr = (((reg2 & DDR_SDRAM_CSn_BNDS_EA_MASK) <<
                    DDR_SDRAM_CSn_BNDS_EA_SHIFT)|0x00FFFFFF);
        printf("  0x%08x - 0x%08x\n\r", startAddr, endAddr);
        if (reg1 & DDR_SDRAM_CSn_CONFIG_AP_EN_MASK)
            printf("  AP_n_EN       = 0x1 - Auto Precharge enabled.\n\r");
        else
            printf("  AP_n_EN       = 0x0 - Auto Precharge disabled.\n\r");
        temp = ((reg1 & DDR_SDRAM_CSn_CONFIG_ROW_MASK) >>
                DDR_SDRAM_CSn_CONFIG_ROW_BIT);
        printf("  ROW_BITS_CS_n = 0x%x", temp);
        switch (temp)
            {
            case 0x0:
                printf(" - 12 row bits.\n\r");
                break;
            case 0x1:
                printf(" - 13 row bits.\n\r");
                break;
            case 0x2:
                printf(" - 14 row bits.\n\r");
                break;
            default:
                printf(" - reserved.\n\r");
                break;
            }
        temp = ((reg1 & DDR_SDRAM_CSn_CONFIG_COLUMN_MASK) >>
                DDR_SDRAM_CSn_CONFIG_COLUMN_BIT);
        printf("  COL_BITS_CS_n = 0x%x", temp);
        switch (temp)
            {
            case 0x0:
                printf(" - 8 column bits.\n\r");
                break;
            case 0x1:
                printf(" - 9 column bits.\n\r");
                break;
            case 0x2:
                printf(" - 10 column bits.\n\r");
                break;
            case 0x3:
                printf(" - 11 column bits.\n\r");
                break;
            default:
                printf(" - reserved.\n\r");
                break;
            }
        }
    else
        printf("  Chip Select 1 is disabled\n\r");

    /* Chip Select 2 */

    printf("\n");
    reg1 = CCSR_READ32(CCSBAR,CCSR_CS2_CONFIG);
    printf("CS2_CONFIG = 0x%08x\n\r", reg1);
    reg2 = CCSR_READ32(CCSBAR,CCSR_CS2_BNDS);
    printf("CS2_BNDS = 0x%08x\n\r", reg2);
    if (reg1 && DDR_SDRAM_CSn_CONFIG_CS_EN_MASK)
        {
        printf("Chip Select 2 is enabled.\n\r");
        startAddr = ((reg2 & DDR_SDRAM_CSn_BNDS_SA_MASK) <<
                     DDR_SDRAM_CSn_BNDS_SA_SHIFT);
        endAddr = (((reg2 & DDR_SDRAM_CSn_BNDS_EA_MASK) <<
                    DDR_SDRAM_CSn_BNDS_EA_SHIFT)|0x00FFFFFF);
        printf("  0x%08x - 0x%08x\n\r", startAddr, endAddr);
        if (reg1 & DDR_SDRAM_CSn_CONFIG_AP_EN_MASK)
            printf("  AP_n_EN       = 0x1 - Auto Precharge enabled.\n\r");
        else
            printf("  AP_n_EN       = 0x0 - Auto Precharge disabled.\n\r");
        temp = ((reg1 & DDR_SDRAM_CSn_CONFIG_ROW_MASK) >>
                DDR_SDRAM_CSn_CONFIG_ROW_BIT);
        printf("  ROW_BITS_CS_n = 0x%x", temp);
        switch (temp)
            {
            case 0x0:
                printf(" - 12 row bits.\n\r");
                break;
            case 0x1:
                printf(" - 13 row bits.\n\r");
                break;
            case 0x2:
                printf(" - 14 row bits.\n\r");
                break;
            default:
                printf(" - reserved.\n\r");
                break;
            }
        temp = ((reg1 & DDR_SDRAM_CSn_CONFIG_COLUMN_MASK) >>
                DDR_SDRAM_CSn_CONFIG_COLUMN_BIT);
        printf("  COL_BITS_CS_n = 0x%x", temp);
        switch (temp)
            {
            case 0x0:
                printf(" - 8 column bits.\n\r");
                break;
            case 0x1:
                printf(" - 9 column bits.\n\r");
                break;
            case 0x2:
                printf(" - 10 column bits.\n\r");
                break;
            case 0x3:
                printf(" - 11 column bits.\n\r");
                break;
            default:
                printf(" - reserved.\n\r");
                break;
            }
        }
    else
        printf("  Chip Select 2 is disabled\n\r");

    /* Chip Select 3 */

    printf("\n");
    reg1 = CCSR_READ32(CCSBAR,CCSR_CS3_CONFIG);
    printf("CS3_CONFIG = 0x%08x\n\r", reg1);
    reg2 = CCSR_READ32(CCSBAR,CCSR_CS3_BNDS);
    printf("CS3_BNDS = 0x%08x\n\r", reg2);
    if (reg1 && DDR_SDRAM_CSn_CONFIG_CS_EN_MASK)
        {
        printf("Chip Select 3 is enabled.\n\r");
        startAddr = ((reg2 & DDR_SDRAM_CSn_BNDS_SA_MASK) <<
                     DDR_SDRAM_CSn_BNDS_SA_SHIFT);
        endAddr = (((reg2 & DDR_SDRAM_CSn_BNDS_EA_MASK) <<
                    DDR_SDRAM_CSn_BNDS_EA_SHIFT)|0x00FFFFFF);
        printf("  0x%08x - 0x%08x\n\r", startAddr, endAddr);
        if (reg1 & DDR_SDRAM_CSn_CONFIG_AP_EN_MASK)
            printf("  AP_n_EN       = 0x1 - Auto Precharge enabled.\n\r");
        else
            printf("  AP_n_EN       = 0x0 - Auto Precharge disabled.\n\r");
        temp = ((reg1 & DDR_SDRAM_CSn_CONFIG_ROW_MASK) >>
                DDR_SDRAM_CSn_CONFIG_ROW_BIT);
        printf("  ROW_BITS_CS_n = 0x%x", temp);
        switch (temp)
            {
            case 0x0:
                printf(" - 12 row bits.\n\r");
                break;
            case 0x1:
                printf(" - 13 row bits.\n\r");
                break;
            case 0x2:
                printf(" - 14 row bits.\n\r");
                break;
            default:
                printf(" - reserved.\n\r");
                break;
            }
        temp = ((reg1 & DDR_SDRAM_CSn_CONFIG_COLUMN_MASK) >>
                DDR_SDRAM_CSn_CONFIG_COLUMN_BIT);
        printf("  COL_BITS_CS_n = 0x%x", temp);
        switch (temp)
            {
            case 0x0:
                printf(" - 8 column bits.\n\r");
                break;
            case 0x1:
                printf(" - 9 column bits.\n\r");
                break;
            case 0x2:
                printf(" - 10 column bits.\n\r");
                break;
            case 0x3:
                printf(" - 11 column bits.\n\r");
                break;
            default:
                printf(" - reserved.\n\r");
                break;
            }
        }
    else
        printf("  Chip Select 3 is disabled\n\r");

    /* DDR SDRAM Timing Configuration 1 */

    printf("\n");
    reg1 = CCSR_READ32(CCSBAR,CCSR_TIMING_CFG_1);
    printf("CCSR_TIMING_CFG_1 = 0x%08x\n\r", reg1);
    temp = ((reg1 & DDR_SDRAM_TIMING_CFG_1_WRTORD_MASK)
            >> DDR_SDRAM_TIMING_CFG_1_WRTORD_BIT);
    printf("  WRTORD   = 0x%x", temp);
    switch (temp)
        {
        case 0x0:
            printf(" - reserved\n\r");
            break;
        default:
            printf(" - %x clocks\n\r", temp);
            break;
        }
    temp = ((reg1 & DDR_SDRAM_TIMING_CFG_1_ACTTOACT_MASK) >>
            DDR_SDRAM_TIMING_CFG_1_ACTTOACT_BIT);
    printf("  ACTTOACT = 0x%x", temp);
    switch (temp)
        {
        case 0x0:
            printf(" - reserved\n\r");
            break;
        case 0x1:
            printf(" - 1 clock\n\r");
            break;
        case 0x2:
            printf(" - 2 clocks\n\r");
            break;
        case 0x3:
            printf(" - 3 clocks\n\r");
            break;
        case 0x4:
            printf(" - 4 clocks\n\r");
            break;
        default:
            printf(" - reserved\n\r");
            break;
        }
    temp = ((reg1 & DDR_SDRAM_TIMING_CFG_1_WRREC_MASK) >>
            DDR_SDRAM_TIMING_CFG_1_WRREC_BIT);
    printf("  WRREC    = 0x%x - %x clocks\n\r", temp);
    temp = ((reg1 & DDR_SDRAM_TIMING_CFG_1_REFREC_MASK) >>
            DDR_SDRAM_TIMING_CFG_1_REFREC_BIT);
    printf("  REFREC   = 0x%x", temp);
    switch (temp)
        {
        case 0x0:
            printf(" - reserved\n\r");
            break;
        default:
            printf(" - %d clocks\n\r", temp + 0x8);
            break;
        }
    temp = ((reg1 & DDR_SDRAM_TIMING_CFG_1_CASLAT_MASK)  >>
            DDR_SDRAM_TIMING_CFG_1_CASLAT_BIT);
    printf("  CASLAT   = 0x%x", temp);
    switch (temp)
        {
        case 0x0:
            printf(" - reserved\n\r");
            break;
        case 0x1:
            printf(" - 1 clock\n\r");
            break;
        case 0x2:
            printf(" - 1.5 clocks\n\r");
            break;
        case 0x3:
            printf(" - 2 clocks\n\r");
            break;
        case 0x4:
            printf(" - 2.5 clocks\n\r");
            break;
        case 0x5:
            printf(" - 3 clocks\n\r");
            break;
        case 0x6:
            printf(" - 3.5 clocks\n\r");
            break;
        default:
            printf(" - 4 clocks\n\r");
            break;
        }
    temp = ((reg1 & DDR_SDRAM_TIMING_CFG_1_ACTTORW_MASK) >>
            DDR_SDRAM_TIMING_CFG_1_ACTTORW_BIT);
    printf("  ACTTORW  = 0x%x", temp);
    switch (temp)
        {
        case 0x0:
            printf(" - reserved\n\r");
            break;
        default:
            printf(" - %x clocks\n\r", temp);
            break;
        }
    temp = ((reg1 & DDR_SDRAM_TIMING_CFG_1_ACTTOPRE_MASK) >>
            DDR_SDRAM_TIMING_CFG_1_ACTTOPRE_BIT);
    printf("  ACTTOPRE = 0x%x", temp);
    switch (temp)
        {
        case 0x0:
            printf(" - reserved\n\r");
            break;
        default:
            printf(" - %d clocks\n\r", temp);
            break;
        }
    temp = ((reg1 & DDR_SDRAM_TIMING_CFG_1_PRETOACT_MASK) >>
            DDR_SDRAM_TIMING_CFG_1_PRETOACT_BIT);
    printf("  PRETOACT = 0x%x", temp);
    switch (temp)
        {
        case 0x0:
            printf(" - reserved\n\r");
            break;
        default:
            printf(" - %x clocks\n\r", temp);
            break;
        }

    /* DDR SDRAM Timing Configuration 2 */

    printf("\n");
    reg1 = CCSR_READ32(CCSBAR,CCSR_TIMING_CFG_2);
    printf("CCSR_TIMING_CFG_2 = 0x%08x\n\r", reg1);
    temp = ((reg1 & DDR_SDRAM_TIMING_CFG_2_WR_DATA_DELAY_MASK) >>
            DDR_SDRAM_TIMING_CFG_2_WR_DATA_DELAY_BIT);
    printf("  WR_DATA_DELAY = 0x%x", temp);
    switch (temp)
        {
        case 0x0:
            printf(" - 0 clock delay\n\r");
            break;
        case 0x1:
            printf(" - 2/8 clock delay (recommended)\n\r");
            break;
        case 0x2:
            printf(" - 4/8 clock delay\n\r");
            break;
        case 0x3:
            printf(" - 6/8 clock delay\n\r");
            break;
        case 0x4:
            printf(" - 1 clock delay\n\r");
            break;
        default:
            printf(" - reserved\n\r");
            break;
        }
    temp = ((reg1 & DDR_SDRAM_TIMING_CFG_2_ACSM_MASK) >>
            DDR_SDRAM_TIMING_CFG_2_ACSM_BIT);
    printf("  ACSM          = 0x%x", temp);
    if (temp)
        {
        printf(" - DRAM address and control buses are shifted by\n\r");
        printf("                        1/2 DRAM cycle before being");
        printf(" driven onto the pins.\n\r");
        }
    else
        {
        printf(" - DRAM address and control buses are output\n\r");
        printf("                        in the default mode.\n\r");
        }
    temp = ((reg1 & DDR_SDRAM_TIMING_CFG_2_CPO_MASK) >>
            DDR_SDRAM_TIMING_CFG_2_CPO_BIT);
    printf("  CPO           = 0x%x", temp);
    switch (temp)
        {
        case 0x0:
            printf(" - CASLAT + 1\n\r");
            break;
        case 0x1:
            printf(" - |CASLAT|\n\r");
            break;
        case 0x2:
            printf(" - |CASLAT| + 1/2\n\r");
            break;
        case 0x3:
            printf(" - |CASLAT| + 1\n\r");
            break;
        case 0x4:
            printf(" - |CASLAT| + 3/2\n\r");
            break;
        case 0x5:
            printf(" - |CASLAT| + 2\n\r");
            break;
        case 0x6:
            printf(" - |CASLAT| + 5/2\n\r");
            break;
        case 0x7:
            printf(" - |CASLAT| + 3\n\r");
            break;
        case 0x8:
            printf(" - |CASLAT| + 7/2\n\r");
            break;
        case 0x9:
            printf(" - |CASLAT| + 4\n\r");
            break;
        case 0xa:
            printf(" - |CASLAT| + 9/2\n\r");
            break;
        case 0xb:
            printf(" - |CASLAT| + 5\n\r");
            break;
        default:
            printf(" - reserved\n\r");
            break;
        }

    /* DDR SDRAM Control Configuration */

    printf("\n");
    reg1 = CCSR_READ32(CCSBAR,CCSR_DDR_SDRAM_CFG);
    printf("CCSR_DDR_SDRAM_CFG = 0x%08x\n\r", reg1);
    temp = ((reg1 & DDR_SDRAM_SDRAM_CFG_2T_EN_MASK) >>
            DDR_SDRAM_SDRAM_CFG_2T_EN_BIT);
    printf("  2T_EN      = 0x%x", temp);
    if (temp)
        printf(" - 2T timing is enabled\n\r");
    else
        printf(" - 1T timing is used\n\r");
    temp = ((reg1 & DDR_SDRAM_SDRAM_CFG_NCAP_MASK) >>
            DDR_SDRAM_SDRAM_CFG_NCAP_BIT);
    printf("  NCAP       = 0x%x", temp);
    if (temp)
        printf(" - DRAMs do not support concurrent auto precharge.\n\r");
    else
        printf(" - DRAMs support concurrent auto precharge.\n\r");
    temp = ((reg1 & DDR_SDRAM_SDRAM_CFG_DYN_PWR_MASK) >>
            DDR_SDRAM_SDRAM_CFG_DYN_PWR_BIT);
    printf("  DYN_PWR    = 0x%x", temp);
    if (temp)
        printf(" - Dynamic power management mode is enabled.\n\r");
    else
        printf(" - Dynamic power management mode is disabled.\n\r");
    temp = ((reg1 & DDR_SDRAM_SDRAM_CFG_SDRAM_TYPE_MASK) >>
            DDR_SDRAM_SDRAM_CFG_SDRAM_TYPE_BIT);
    printf("  SDRAM_TYPE = 0x%x", temp);
    if (temp == 0x2)
        printf(" - DDR SDRAM\n\r");
    else
        printf(" - reserved\n\r");
    temp = ((reg1 & DDR_SDRAM_SDRAM_CFG_RD_EN_MASK) >>
            DDR_SDRAM_SDRAM_CFG_RD_EN_BIT);
    printf("  RD_EN      = 0x%x", temp);
    if (temp)
        printf(" - registered DIMMs\n\r");
    else
        printf(" - unbuffered DIMMs\n\r");
    temp = ((reg1 & DDR_SDRAM_SDRAM_CFG_ECC_EN_MASK) >>
            DDR_SDRAM_SDRAM_CFG_ECC_EN_BIT);
    printf("  ECC_EN     = 0x%x", temp);
    if (temp)
        printf(" - ECC is enabled\n\r");
    else
        printf(" - No ECC errors are reported\n\r");
    temp = ((reg1 & DDR_SDRAM_SDRAM_CFG_SREN_MASK) >>
            DDR_SDRAM_SDRAM_CFG_SREN_BIT);
    printf("  SREN       = 0x%x", temp);
    if (temp)
        printf(" - SDRAM self refresh enabled during sleep or soft-stop\n\r");
    else
        printf(" - SDRAM self refresh disabled during sleep or soft-stop\n\r");
    temp = ((reg1 & DDR_SDRAM_SDRAM_CFG_MEM_EN_MASK) >>
            DDR_SDRAM_SDRAM_CFG_MEM_EN_BIT);
    printf("  MEM_EN     = 0x%x", temp);
    if (temp)
        printf(" - SDRAM interface logic is enabled\n\r");
    else
        printf(" - SDRAM interface logic is disabled\n\r");

    /* DDR SDRAM Mode Configuration */

    printf("\n");
    reg1 = CCSR_READ32(CCSBAR,CCSR_DDR_SDRAM_MODE);
    printf("CCSR_DDR_SDRAM_MODE = 0x%08x\n\r", reg1);
    printf("  SDMODE  = 0x%04x\n\r",((reg1 &
        DDR_SDRAM_SDRAM_MODE_SDMODE_MASK) >>
        DDR_SDRAM_SDRAM_MODE_SDMODE_BIT));
    printf("  ESDMODE = 0x%04x\n\r",((reg1 &
        DDR_SDRAM_SDRAM_MODE_ESDMODE_MASK) >>
        DDR_SDRAM_SDRAM_MODE_ESDMODE_BIT));

    /* DDR SDRAM Interval Configuration */

    printf("\n");
    reg1 = CCSR_READ32(CCSBAR,CCSR_DDR_SDRAM_INTERVAL);
    printf("CCSR_DDR_SDRAM_INTERVAL = 0x%08x\n\r", reg1);
    printf("  BSTOPRE = 0x%04x\n\r",((reg1 &
        DDR_SDRAM_SDRAM_INTERVAL_BSTOPRE_MASK) >>
        DDR_SDRAM_SDRAM_INTERVAL_BSTOPRE_BIT));
    printf("  REFINT  = 0x%04x\n\r",((reg1 &
        DDR_SDRAM_SDRAM_INTERVAL_REFINT_MASK) >>
        DDR_SDRAM_SDRAM_INTERVAL_REFINT_BIT));

    /* Memory Data Path Error Injection Mask High */

    printf("\n");
    reg1 = CCSR_READ32(CCSBAR,CCSR_DATA_ERR_INJECT_HI);
    printf("CCSR_DATA_ERR_INJECT_HI = 0x%08x\n\r", reg1);

    /* Memory Data Path Error Injection Mask Low */

    printf("\n");
    reg1 = CCSR_READ32(CCSBAR,CCSR_DATA_ERR_INJECT_LO);
    printf("CCSR_DATA_ERR_INJECT_LO = 0x%08x\n\r", reg1);

    /* Memory Data Path Error Injection Mask ECC */

    printf("\n");
    reg1 = CCSR_READ32(CCSBAR,CCSR_ECC_ERR_INJECT);
    printf("CCSR_ECC_ERR_INJECT = 0x%08x\n\r", reg1);
    printf("  EEIM = 0x%02x (ECC error injection mask)\n\r",((reg1 &
        DDR_SDRAM_ECC_ERR_INJECT_EEIM_MASK) >>
        DDR_SDRAM_ECC_ERR_INJECT_EEIM_BIT));
    temp = ((reg1 & DDR_SDRAM_ECC_ERR_INJECT_EIEN_MASK) >>
            DDR_SDRAM_ECC_ERR_INJECT_EIEN_BIT);
    printf("  EIEN = 0x%x", temp);
    if (temp)
        printf("  - error injection enabled\n\r");
    else
        printf("  - error injection disabled\n\r");
    temp = ((reg1 & DDR_SDRAM_ECC_ERR_INJECT_EMB_MASK) >>
            DDR_SDRAM_ECC_ERR_INJECT_EMB_BIT);
    printf("  EMB  = 0x%x", temp);
    if (temp)
        printf("  - Mirror most significant data path byte onto ECC byte\n\r");
    else
        printf("  - Mirror byte functionality disabled\n\r");

    /* Memory Data Path Read Capture High */

    printf("\n");
    reg1 = CCSR_READ32(CCSBAR,CCSR_CAPTURE_DATA_HI);
    printf("CCSR_CAPTURE_DATA_HI = 0x%08x\n\r", reg1);

    /* Memory Data Path Read Capture Low */

    printf("\n");
    reg1 = CCSR_READ32(CCSBAR,CCSR_CAPTURE_DATA_LO);
    printf("CCSR_CAPTURE_DATA_LO = 0x%08x\n\r", reg1);

    /* Memory Data Path Read Capture ECC */

    printf("\n");
    reg1 = CCSR_READ32(CCSBAR,CCSR_CAPTURE_ECC);
    printf("CCSR_CAPTURE_ECC = 0x%08x\n\r", reg1);
    printf("  ECE = 0x%02x\n\r",((reg1 &
        DDR_SDRAM_CAPTURE_ECC_ECE_MASK) >>
        DDR_SDRAM_CAPTURE_ECC_ECE_BIT));

    /* Memory Error Detect */

    printf("\n");
    reg1 = CCSR_READ32(CCSBAR,CCSR_ERR_DETECT);
    printf("CCSR_ERR_DETECT = 0x%08x\n\r", reg1);
    temp = ((reg1 & DDR_SDRAM_ERR_DETECT_MSE_MASK) >>
            DDR_SDRAM_ERR_DETECT_MSE_BIT);
    printf("  MSE = 0x%x", temp);
    if (temp)
        printf(" - memory select error has been detected\n\r");
    else
        printf(" - memory select error has not been detected\n\r");
    temp = ((reg1 & DDR_SDRAM_ERR_DETECT_SBE_MASK) >>
            DDR_SDRAM_ERR_DETECT_SBE_BIT);
    printf("  SBE = 0x%x", temp);
    if (temp)
        {
        printf(" - number of single-bit ECC errors detected has crossed\n\r");
        printf("              the threshold set in ERR_SBE[SBET]\n\r");
        }
    else
        {
        printf(" - number of single-bit ECC errors detected has not\n\r");
        printf("              crossed threshold set in ERR_SBE[SBET]\n\r");
        }
    temp = ((reg1 & DDR_SDRAM_ERR_DETECT_MBE_MASK) >>
            DDR_SDRAM_ERR_DETECT_MBE_BIT);
    printf("  MBE = 0x%x", temp);
    if (temp)
        printf(" - multiple-bit error has been detected\n\r");
    else
        printf(" - multiple-bit error has not been detected\n\r");
    temp = ((reg1 & DDR_SDRAM_ERR_DETECT_MME_MASK) >>
            DDR_SDRAM_ERR_DETECT_MME_BIT);
    printf("  MME = 0x%x", temp);
    if (temp)
        printf(" - multiple memory errors of same type were detected\n\r");
    else
        printf(" - multiple memory errors of same type were not detected\n\r");

    /* Memory Error Disable */

    printf("\n");
    reg1 = CCSR_READ32(CCSBAR,CCSR_ERR_DISABLE);
    printf("CCSR_ERR_DISABLE = 0x%08x\n\r", reg1);
    temp = ((reg1 & DDR_SDRAM_ERR_DISABLE_MSED_MASK) >>
            DDR_SDRAM_ERR_DISABLE_MSED_BIT);
    printf("  MSED = 0x%x", temp);
    if (temp)
        printf(" - memory select errors are disabled\n\r");
    else
        printf(" - memory select errors are enabled\n\r");
    temp = ((reg1 & DDR_SDRAM_ERR_DISABLE_SBED_MASK) >>
            DDR_SDRAM_ERR_DISABLE_SBED_BIT);
    printf("  SBED = 0x%x", temp);
    if (temp)
        printf(" - single-bit ECC errors are disabled\n\r");
    else
        printf(" - single-bit ECC errors are enabled\n\r");
    temp = ((reg1 & DDR_SDRAM_ERR_DISABLE_MBED_MASK) >>
            DDR_SDRAM_ERR_DISABLE_MBED_BIT);
    printf("  MBED = 0x%x", temp);
    if (temp)
        printf(" - multiple-bit ECC errors are not detected or reported\n\r");
    else
        printf(" - multiple-bit ECC errors are detected and/or reported\n\r");

    /* Memory Error Interrupt Enable */

    printf("\n");
    reg1 = CCSR_READ32(CCSBAR,CCSR_ERR_INT_EN);
    printf("CCSR_ERR_INT_EN = 0x%08x\n\r", reg1);
    temp = ((reg1 & DDR_SDRAM_ERR_INT_EN_MSEE_MASK) >>
            DDR_SDRAM_ERR_INT_EN_MSEE_BIT);
    printf("  MSEE = 0x%x", temp);
    if (temp)
        printf(" - memory select errors generate interrupts\n\r");
    else
        printf(" - memory select errors do not cause interrupts\n\r");
    temp = ((reg1 & DDR_SDRAM_ERR_INT_EN_SBEE_MASK) >>
            DDR_SDRAM_ERR_INT_EN_SBEE_BIT);
    printf("  SBEE = 0x%x", temp);
    if (temp)
        printf(" - single-bit ECC errors generate interrupts\n\r");
    else
        printf(" - single-bit ECC errors cannot generate interrupts\n\r");
    temp = ((reg1 & DDR_SDRAM_ERR_INT_EN_MBEE_MASK) >>
            DDR_SDRAM_ERR_INT_EN_MBEE_BIT);
    printf("  MBEE = 0x%x", temp);
    if (temp)
        printf(" - multiple-bit ECC errors generate interrupts\n\r");
    else
        printf(" - multiple-bit ECC errors cannot generate interrupts\n\r");

    /* Memory Error Attributes Capture */

    printf("\n");
    reg1 = CCSR_READ32(CCSBAR,CCSR_CAPTURE_ATTRIBUTES);
    printf("CCSR_CAPTURE_ATTRIBUTES = 0x%08x\n\r", reg1);
    temp = ((reg1 & DDR_SDRAM_CAPTURE_ATTRIBUTES_VLD_MASK) >>
            DDR_SDRAM_CAPTURE_ATTRIBUTES_VLD_BIT);
    printf("  VLD  = 0x%x ", temp);
    if (temp)
        printf(" - valid information captured in error capture registers\n\r");
    else
        printf(" - no valid information in error capture registers\n\r");
    temp = ((reg1 & DDR_SDRAM_CAPTURE_ATTRIBUTES_TTYP_MASK) >>
            DDR_SDRAM_CAPTURE_ATTRIBUTES_TTYP_BIT);
    printf("  TTYP = 0x%x ", temp);
    switch (temp)
        {
        case 0x0:
            printf(" - reserved\n\r");
            break;
        case 0x1:
            printf(" - transaction type for error is write\n\r");
            break;
        case 0x2:
            printf(" - transaction type for error is read\n\r");
            break;
        default:
            printf(" - transaction type for error is read-modify-write\n\r");
            break;
        }
    temp = ((reg1 & DDR_SDRAM_CAPTURE_ATTRIBUTES_TSRC_MASK) >>
            DDR_SDRAM_CAPTURE_ATTRIBUTES_TSRC_BIT);
    printf("  TSRC = 0x%02x", temp);
    switch (temp)
        {
        case 0x0:
            printf(" - PCI\n\r");
            break;
        case 0x4:
            printf(" - Local Bus\n\r");
            break;
        case 0x8:
            printf(" - Configuration Space\n\r");
            break;
        case 0xa:
            printf(" - Boot sequencer\n\r");
            break;
        case 0xc:
            printf(" - RapidIO\n\r");
            break;
        case 0x10:
            printf(" - Processor (instruction)\n\r");
            break;
        case 0x11:
            printf(" - Processor (data)\n\r");
            break;
        case 0x15:
            printf(" - DMA\n\r");
            break;
        case 0x17:
            printf(" - SAP\n\r");
            break;
        case 0x18:
            printf(" - TSEC 1\n\r");
            break;
        case 0x19:
            printf(" - TSEC 2\n\r");
            break;
        case 0x1a:
            printf(" - FEC\n\r");
            break;
        case 0x1c:
            printf(" - RapidIO message units\n\r");
            break;
        case 0x1d:
            printf(" - RapidIO doorbell units\n\r");
            break;
        case 0x1e:
            printf(" - RapidIO port-write units\n\r");
            break;
        default:
            printf(" - reserved\n\r");
            break;
        }
    printf("  TSIZ = 0x%x\n\r",((reg1 &
        DDR_SDRAM_CAPTURE_ATTRIBUTES_TSIZ_MASK) >>
        DDR_SDRAM_CAPTURE_ATTRIBUTES_TSIZ_BIT));
    printf("  BNUM = 0x%x\n\r",((reg1 &
        DDR_SDRAM_CAPTURE_ATTRIBUTES_BNUM_MASK) >>
        DDR_SDRAM_CAPTURE_ATTRIBUTES_BNUM_BIT));

    /* Memory Error Address Capture */

    printf("\n");
    reg1 = CCSR_READ32(CCSBAR,CCSR_CAPTURE_ADDRESS);
    printf("CCSR_CAPTURE_ADDRESS = 0x%08x\n\r", reg1);

    /* Single-Bit ECC Memory Error Management */

    printf("\n");
    reg1 = CCSR_READ32(CCSBAR,CCSR_ERR_SBE);
    printf("CCSR_ERR_SBE = 0x%08x\n\r", reg1);
    printf("  SBEC = 0x%02x\n\r",((reg1 &
        DDR_SDRAM_ERR_SBE_SBEC_MASK) >>
        DDR_SDRAM_ERR_SBE_SBEC_BIT));
    printf("  SBET = 0x%02x\n\r",((reg1 &
        DDR_SDRAM_ERR_SBE_SBET_MASK) >>
        DDR_SDRAM_ERR_SBE_SBET_BIT));
    }

/******************************************************************************
*
* mpc8540Show - "Show" the names of all of the "show" routines for mpc8540.
*
* This function displays the "show" and "dump" functions which can be 
* called to produce various dipslays.  A short description of each display
* or dump routine is also presented.
*
* RETURNS: NA
*/

void mpc8540Show (void)
    {
    LOCAL char * showString =
    "\n\n"
    "AVAILABLE mpc8540 \"show\" and \"dump\" routines:\n"
    "\n"
    "\n"
    "mpc8540MemRegDump (): Dumps in raw format the entire mpc8540\n"
    "                      Memory mapped register set.  The individual\n"
    "                      components registers can be dumped\n"
    "                      individually by invoking the following\n"
    "                      routines:\n"
    "\n"
    "  mpc8540CcsDump ():       Mpc8540 Command Control and Status\n"
    "  mpc8540LawDump ():       Local Access (LAW)\n"
    "  mpc8540EcmDump ():       e500 Coherence Module\n"
    "  mpc8540DdrCtlDump ():    DDR Memory Controller\n"
    "  mpc8540I2cDump ():       I2c\n"
    "  mpc8540DuartDump ():     DUART\n"
    "  mpc8540LbcDump ():       Local Bus Controller\n"
    "  mpc8540PciAccDump ():    PCI Configuration Access\n"
    "  mpc8540PciATMUDump ():   PCI Address Translation Mapping\n"
    "  mpc8540PciErrDump ():    PCI Error\n"
    "  mpc8540L2SramDump ():    L2 SRAM\n"
    "  mpc8540DmaDump ():       DMA\n"
    "  mpc8540Tsec1Dump ():     Three Speed Ethernet Controller 1\n"
    "  mpc8540Tsec2Dump ():     Three Speed Ethernet Controller 2\n"
    "  mpc8540FecDump ():       Fast Ethernet Controller\n"
    "  mpc8540PicGlblDump ():   Programmable Interrupt Controller Global\n"
    "  mpc8540PicIntlDump ():   Programmable Interrupt Controller Internal\n"
    "  mpc8540PicPerCPUDump (): Programmable Interrupt Controller per-CPU\n"
    "  mpc8540RapidIoDump ():   RapidIO\n"
    "  mpc8540GlblUtilDump ():  Global Utilities\n"
    "  mpc8540PerfMonDump ():   Performance Management\n"
    "  mpc8540DbugWpDump ():    Debug/Watchpoint\n"
    "\n"
    "The following are formatted \"show\" routines:\n"
    "\n"
    "\n"
    "coreLbcShow ():    Local Bus Controller\n"
    "coreShow ():       Various \"core\" features\n"
    "mpc8540DdrCtlShow ():    DDR SDRAM Memory Controller\n"
    "tlbAllShow ():     Both Translation Lookaside Buffer sets (0 and 1)\n"
    "                       Calls the following function:\n"
    "\n"
    "  tlbShow (n):       One Translation Lookaside Buffer set (n = 0 or 1)\n"
    "\n"
    "lawAllShow ():     Local Access Windows\n"
    "pciAtmuAllShow (): All (in and out) PCI access\n"
    "                   Calls the following functions:\n"
    "\n"
    "  pciAtmuOutShow ():     PCI outbound access\n"
    "  pciAtmuInShow ():      PCI inbound access\n"
    "\n"
    "\n"
    ;

    printf("%s",showString);

    }
